/*

 JSParsec - A parser combinator library for JavaScript

 Version: 1.0.1

 http://code.google.com/p/jsparsec/

 Copyright (c) 2010 Balazs Endresz (balazs.endresz@gmail.com)
 Dual licensed under the MIT and GPL licenses.


 The initial implementation of some combinators and the memoization is derived from:
 http://www.bluishcoder.co.nz/2007/10/javascript-parser-combinators.html

 Most functions should behave like their counterparts in Parsec:
 http://www.haskell.org/haskellwiki/Parsec

*/
(function(){function wa(a){function b(){var c=H(arguments);return c.length>=(a._length===y?a.length:a._length)?a.apply(null,c):function(){return b.apply(null,c.concat(H(arguments)))}}return b}function Jb(a){return function(){return a}}function xa(a){return Fc.call(a)=="[object Array]"}function Va(a){return a!==y}function H(a,b){return Gc.call(a,b||0)}function Wa(a,b,c){for(var d=0,e=c.length;d<e;++d)b=a(b,c[d]);return b}function ya(a,b,c){for(var d=c.length-1;d>-1;--d)b=a(c[d],b);return b}function G(a,
b){for(var c=[],d=0,e=b.length;d<e;++d)c[d]=a(b[d],d);return c}function Kb(a,b){for(var c=[],d=0,e=a.length;d<e;++d)b(a[d])&&c.push(a[d]);return c}function Xa(a,b){var c=a.length;if(!c)return-1;for(var d=0;d<c;d++)if(a[d]===b)return d;return-1}function Lb(a,b){var c=a.length;if(!c)return-1;for(c=c-1;c>-1;--c)if(a[c]===b)return c;return-1}function Ya(a,b){for(var c=[],d=0,e=Math.min(a.length,b.length);d<e;++d)c[d]=[a[d],b[d]];return c}function Za(a){if(a.sort)return a.sort();return H(a).sort().join("")}
function Na(a,b){b=b===y?[]:b;var c=a[0],d=H(a,1);return!a.length?[]:Oa(c,b)?Na(d,b):I(c,Na(d,I(c,b)))}function Mb(a,b,c){if(c.Nothing)return a;if(c.Just)return b(c[0])}function Nb(a,b){return a===b?Ea.EQ:a<=b?Ea.LT:Ea.GT}function C(a,b){for(var c in b)a[c]=b[c];return a}function Ob(a,b){return function(){return a(b.apply(null,arguments))}}function Pb(a,b){return function(c){var d=H(arguments,1);d.unshift(b(c));return a.apply(null,d)}}function $a(a){return function(b,c){return a(c,b)}}function I(a,
b){if(typeof a=="string"&&typeof b=="string")return a+b;return[a].concat(b)}function ab(a,b){if(typeof a=="string"&&typeof b=="string")return a+b;return a+b.join("")}function bb(a,b){for(var c=[],d=0;d<a;++d)c[d]=b;return c}function Qb(a){return-a}function cb(a){return!a.length}function Oa(a,b){return(b.indexOf?b.indexOf(a):Xa(b,a))!=-1}function db(a){return/^\s$/.test(a)}function Rb(a){return a.toUpperCase()==a}function Sb(a){return a.toLowerCase()==a}function Tb(a){return/^\w$/.test(a)}function eb(a){return/^\w$/.test(a)&&
/^\D$/.test(a)}function Ub(a){return/^\d$/.test(a)}function Vb(a){return/^[0-9A-Fa-f]$/.test(a)}function Wb(a){return/^[0-7]$/.test(a)}function fb(a){return parseInt(a,16)}function Hc(a,b){return{indexOf:function(c){return c>=a&&c<=b?true:-1},toString:function(){return"range("+a+", "+b+")"}}}function Ic(a){return a[0]}function Jc(a){return a[1]}function Kc(a){return function(b){return a(b[0],b[1])}}function Lc(a,b){var c=b.length;if(!c)return R.Nothing;for(var d=0;d<c;++d)if(b[d][0]===a)return R.Just(b[d][1]);
return R.Nothing}function Mc(a){return parseInt(a.join?a.join(""):a,16)}function Nc(a){return parseInt(a.join?a.join(""):a,8)}function Oc(){var a,b;G(function(c){b=c.split(".");a=window[b[0]]=window[b[0]]||{};G(function(d){a=a[d]=a[d]||{}},b.slice(1))},arguments);return a}function Xb(){}function Pc(a,b){if(!/^[0-9]$/.test(b))return b;if(typeof a!="object")return b;var c=0;for(var d in a){if(a.hasOwnProperty(d)&&c==b)return d;c++}return-1}function Pa(){}function Yb(a){return function(){var b=[],c=
this._recordset;if(c&&!xa(c)){for(var d in c){var e=a?c[d].name||c[d]:this[d];if(!a&&e instanceof Function)e=e.constructor!=Function?e.constructor.name:"Function("+e.name+")";b.push(d+" :: "+e)}c=bb(this._dataConstructor.length+2," ").join("");b="{"+b.join("\n"+c+",")+"\n"+c+"}"}else{for(d=0;d in this;d++)b.push(a?c[d].name||c[d]:this[d]);b=b.join(" ")}return"("+this._dataConstructor+(b?" ":"")+b+")"}}function fa(a,b){function c(j,i){function o(A,u){var B=A instanceof Xb,S=B?u:H(arguments),M=new a,
J=0;M.constructor=a;M._recordset=p&&i[0]||i;M._dataConstructor=j;M.update=function(ga){var $={};for(var Q in i[0]){$[Q]=this[Q];if(Q in ga)$[Q]=ga[Q]}return o(za,$)};M[j]=true;if(S!==y)for(var N in S)if(S.hasOwnProperty(N)&&N!=j){if(B&&i&&p)if(!(N in i[0]))throw"The accessor '"+N+"' is not defined for the data constructor '"+j+"'";var aa=Pc(i[0],N),ba=S[J]!==undefined?S[J]:S[aa],U=p?i[0][aa]:i[J];if(U.name&&!(U==ba.constructor||ba instanceof U))throw"Type error: expecting '"+U.name+"' instead of '"+
ba.constructor.name+"' in the argument '"+(aa||J)+"' of the data constructor '"+j+"' of type '"+a.name+"'";M[aa]=M[J]=M[N]=S[N];J++}else if(N==j)throw"Accessor has the same name as the data constructor: '"+j+"'";return M}var p=i&&typeof i[0]=="object";return o}if(a.constructors)throw"Type constructor has been already defined: '"+a.name+"'";a.constructors=b;a.prototype=new Pa;for(var d=0,e=b.length;d<e;++d){var g=typeof b[d]!="object",h=g?b[d]:b[d][0];if(h in a)throw"The name of the data constructor ("+
h+") is invalid!";a[h]=g?c(h)():c(h,H(b[d],1));if(!g)a[h]._length=H(b[d],1).length}}function R(){}function Ea(){}function Aa(){}function ca(a){return["l",a]}function oa(a){return["r",a]}function Zb(a){return["x",a]}function Qc(a){if(a)if(!a._String){var b=Ba[a];if(a._Op&&!b)return"l";return b&&(b.fixity[0]||"l")}}function Rc(a){if(a)if(!a._String){var b=Ba[a];if(a._Op&&!b)return 9;return b&&(Va(b.fixity[1])?b.fixity[1]:9)}}function gb(a,b,c){var d;if(a[b]._Op){delete a[b]._Op;d=a[b]}else d=Ba[a[b]].func;
d=d(a[b-1],a[b+1]);a.splice(b-1,3,d);return ha(a,c)}function Sc(a){a._Array=true;return a}function Tc(a){a=new String(a);a._String=true;return a}function Uc(a){a._Op=true;return a}function ha(a,b){a=G(function(i){if(i&&i._Array){delete i._Array;return i}return xa(i)?ha(i,b):i&&i.CallStream?i.resolve(b):i},a);if(b)a=G(function(i){return i instanceof hb?b:i},a);for(var c=[],d=[],e=0,g=a.length;e<g;++e){var h=a[e],j=false;if(Ba[h])j=true;if(h&&h._String){j=false;h=h.toString()}if(h&&h._Op)j=true;if(!j&&
e!=g-1)c.push(h);else{e==g-1&&c.push(h);c=c.length>1?c[0].apply(null,c.slice(1)):c[0];d.push(c);e!=g-1&&d.push(h);c=[]}}a=d;d=G(Qc,a);g=G(Rc,a);h=Kb(g,Va).sort().pop();e=Xa(g,h);g=Lb(g,h);return d[e]=="l"?gb(a,e,b):d[g]=="r"?gb(a,g,b):d[e]=="x"?gb(a,e,b):a[0]}function v(){function a(){return d.apply(null,arguments)}function b(){return(e?d:b.resolve()).apply(null,arguments)}var c=arguments,d,e;b.resolve=function(g){if(e)return d;d=ha(c,g||a);c=null;e=true;return d};b.CallStream=true;b.constructor=
r;return b}function hb(){}function m(){function a(g,h,j){return d(g,h,j)}function b(g,h,j){if(e||g instanceof Fa)return(e?d:b.resolve())(g,h,j);c.push(ha(arguments,a));return b}var c=[],d,e;c.push(ha(arguments,a));b.resolve=function(){if(e)return d;d=k.apply(null,c);e=true;c=null;return d};b.CallStream=true;b.constructor=r;return b}function Fa(a,b){this.input=a;this.index=b||0;this.length=a.length-this.index;this.cache={};return this}function $b(a){return new Fa(a)}function E(a,b,c){return{ast:a,
success:b===y?true:b,expecting:c}}function Ga(a){return E(y,false,a)}function ib(a){return function(b,c,d){return d(E(null,false,{unexpected:a}))}}function Vc(a){return function(b,c,d){return d(E(null,false,{unexpected:c[a]}))}}function ac(a){return function(b,c,d){return d(E(y,false,a))}}function bc(a,b,c){return c(E(y,false))}function jb(a){return typeof a=="string"?V(a):xa(a)?ha(a):a}function Wc(a){for(;a&&a.func;)a=a.func.apply(null,a.args||[])}function kb(a,b){b=b||0;b++;if(a&&a.func){a=a.func.apply(null,
a.args||[]);b%500==0?setTimeout(function(){kb(a,b)},1):kb(a,b)}else b=0}function Xc(a,b,c,d,e){var g=b instanceof Fa?b:$b(b);(e?kb:Wc)({func:a,args:[g,{},function(h){h.state=g;delete h.index;delete h.length;if(h.success){delete h.error;delete h.expecting}else{h.error=lb(h.expecting,h.state);d&&d(h.error)}c(h)}]})}function lb(a,b,c,d){c=c===undefined?b.index:c;if(typeof a=="string"){var e=b.input.split("\n"),g=e.length,h=b.input.substr(c).split("\n").length;g=g-h+1;e=c-e.splice(0,g-1).join("\n").length;
b=d||b.input.substr(c,a.length).substr(0,6);return'Unexpected "'+(b.length?b:"end of file")+(d?"":'", expecting "'+a)+'" at line '+g+" char "+e}if(xa(a)){a=G(function(j){return typeof j=="object"?j.expecting:j},a);return lb(a.join('" or "'),b)}else if(typeof a=="object")return lb(a.expecting,b,a.at,a.unexpected)}function r(){}function mb(a,b){return function(c,d,e){return{func:a,args:[c,d,function(g){return g.success?{func:b(g.ast),args:[c,d,e]}:e(g)}]}}}function q(a,b){if(a=="scope")throw"Can't use 'scope' as an identifier!";
return function(c,d,e){return{func:b,args:[c,d,function(g){if(g.success)d[a]=g.ast;g=C({},g);return e(g)}]}}}function t(a,b){b&&H(arguments);return function(c,d,e){return{func:function(){var g;if(typeof a=="string"){if(!(a in d))throw'Not in scope: "'+a+'"';g=d[a]}else g=a(d);return e(E(g))}}}}function nb(a){var b=H(arguments,1);return function(c){return a.apply(null,G(function(d){return c[d]},b))}}function cc(a,b,c){return c(E(a.index))}function dc(a){var b=typeof a;return function(c,d,e){c.scrollTo(b==
"string"?d[a]:a);return e(Yc)}}function ec(a){return function(b,c,d){return d(E(a))}}function fc(a,b){return k(q("a",a),q("b",b),t(function(c){return c.a(c.b)}))}function ob(a,b){return k(q("x1",b),O(a,"x1"))}function pb(a,b,c){return k(q("x1",b),q("x2",c),O(a,"x1","x2"))}function gc(a,b,c,d){return k(q("x1",b),q("x2",c),q("x3",d),O(a,"x1","x2","x3"))}function hc(a,b){return k(q("a",a),b,t("a"))}function w(a,b){function c(d,e,g){return{func:a,args:[d,e,function(h){function j(o){var p=o.expecting;
if(p)if(xa(p))i=i.concat(p);else i.push(p);if(o.success)delete o.expecting;else o.expecting=i}var i=[];j(h);return h.ast!==y?{func:g,args:[h]}:{func:b,args:[d,e,function(o){j(o);return g(o)}]}}]}}c.constructor=r;return c}function Zc(){var a=G(jb,arguments);return function(b,c,d){for(var e=1,g=a.length,h=a[0];e<g;++e)h=w(h,a[e]);return h(b,c,d)}}function ic(a){return function(b,c,d){function e(i){return function(o,p,A){return{func:i,args:[o,p,function(u){g++;if(!u.success)return A(u);u.ast!==y&&h.push(u.ast);
return g<j?e(a[g])(o,p,A):A(u)}]}}}var g=0,h=[],j=a.length;return{func:e(a[g]),args:[b,c,function(i){i=C({},i);i.ast=h;i.success&&delete i.expecting;return d(i)}]}}}function jc(a){return function(b){return function(c,d,e){function g(i){return function(o,p,A){return{func:i,args:[o,p,function(u){if(!u.success)return A(u);h=true;u.ast!==y&&j.push(u.ast);return g(i)(o,p,A)}]}}}var h=false,j=[];return{func:g(b),args:[c,d,function(i){i=C({},i);i.success=!a||h&&a;i.ast=j;if(i.success)delete i.expecting;
else i.ast=y;return e(i)}]}}}}function qb(a){return function(b){var c=kc++,d=function(e,g,h){g=e.index;var j=e.getCached(c);if(j!==y)return h(j);j=a(b,e,g);e.putCached(c,g,j);return h(j)};d.constructor=r;return d}}function Qa(a){return function(b,c){var d=kc++,e=function(g,h,j){var i=g.index,o=g.getCached(d);if(o!==y)return j(o);return{func:b,args:[g,h,function(p){p=a(c,p,g,i);g.putCached(d,i,p);return j(p)}]}};e.constructor=r;return e}}function lc(a){function b(c,d){return k(q("x",c),q("xs",d),t(nb(I,
"x","xs")))}return ya(b,n([]),a)}function $c(a){return function(b,c,d){return a()(b,c,d)}}function ia(a){return ya(w,rb,a)}function Ra(a,b){return w(b,n(a))}function ad(a){return Ra(R.Nothing,ob(R.Just,a))}function bd(a){return w(k(a,n(null)),n(null))}function Sa(a){return k(a,ja(a))}function sb(a,b){return w(Ta(a,b),n([]))}function Ta(a,b){return k(q("x",a),q("xs",pa(k(b,a))),O(I,"x","xs"))}function mc(a,b){return k(q("x",a),w(k(b,q("xs",function(c,d,e){return nc(a,b)(c,d,e)}),t(function(c){return I(c.scope.x,
c.xs)})),t(function(c){return[c.x]})))}function nc(a,b){return w(mc(a,b),n([]))}function cd(a,b){return Ha(k(q("x",a),b,t("x")))}function dd(a,b){return pa(k(q("x",a),b,t("x")))}function ed(a,b){return a<=0?n([]):lc(bb(a,b))}function fd(a,b,c){return w(oc(a,b),n(c))}function gd(a,b,c){return w(pc(a,b),n(c))}function pc(a,b){function c(d){var e=k(q("f",b),q("y",a),function(g,h,j){return c(h.f(d,h.y))(g,h,j)});return w(e,n(d))}return k(q("x",a),function(d,e,g){return c(e.x)(d,e,g)})}function oc(a,b){function c(e){var g=
k(q("f",b),q("y",d),function(h,j,i){return i(E(j.f(e,j.y)))});return w(g,n(e))}var d=k(q("x",a),function(e,g,h){return c(g.x)(e,g,h)});return d}function hd(a,b,c){b=a.at(0);if(b.length){a.scroll(1);return c(E(b))}return c(Ga("anyToken"))}function id(a,b,c){return c(E(y,!a.length,a.length?"end of input":y))}function tb(a){return P(w(k(q("c",P(a)),Vc("c")),n(null)))}function jd(a,b){function c(e,g,h){return d(e,g,h)}var d=w(k(b,n([])),k(q("x",a),q("xs",c),O(I,"x","xs")));return d}function kd(a){return k(q("state",
qc),q("x",a),rc("state"),t("x"))}function Ia(){}function ub(){}function vb(a){function b(f){return c(V(f))}function c(f){return k(q("x",f),sc,t("x"))}function d(f,l,x){return tc(f,l,x)}function e(f,l,x){return uc(f,l,x)}function g(f,l,x){return wb(f,l,x)}function h(f){return qa(b("("),b(")"),f)}function j(f){return qa(b("{"),b("}"),f)}function i(f){return qa(b("<"),b(">"),f)}function o(f){return qa(b("["),b("]"),f)}function p(f){return sb(f,xb)}function A(f){return sb(f,yb)}function u(f){return Ta(f,
xb)}function B(f){return Ta(f,yb)}function S(f){return k(s(f[0]),n(f[1]))}function M(f){return P(k(V(f[0]),n(f[1])))}function J(f,l){return m("digits","<-",Ha,l)(t,function(x){return Wa(function(K,Ja){return f*K+vc(fb(Ja))},0,x.digits)})}function N(f,l,x){return ra(f,l,x)}function aa(f,l){return(l+wc(fb(f)))/10}function ba(f){return f<0?1/ba(-f):Ka(Math.pow(10,f))}function U(f){return v(m("fract","<-",ld)("expo","<-",Ra,1,xc)(t,function(l){return Ka(f+l.fract)*l.expo}),"<|>",m("expo","<-",xc)(t,function(l){return Ka(f)*
l.expo}))}function ga(f){return m("f","<-",U,f)(O,Aa.Right,"f")}function $(f){return v(c,"$",P,"$",m(V(f))(tb,a.opLetter,"<?>","end of "+f))}function Q(f){return Ca(Za(a.reservedOpNames),f)}function D(f){function l(K){return!K.length?n(null):k(sa(x(K[0]),""+f),l(H(K,1)))}function x(K){return eb(K)?w(s(K.toLowerCase()),s(K.toUpperCase())):s(K)}return a.caseSensitive?V(f):k(l(f),n(f))}function da(f){return v(c,"$",P,"$",m(D(f))(tb,a.identLetter,"<?>","end of "+f))}function Ca(f,l){function x(K){if(!K.length)return false;
var Ja=Nb(K[0],l);return Ja.LT?x(H(K,1)):Ja.EQ?true:Ja.GT?false:null}return x(f)}function zb(f){f=a.caseSensitive?f:f.toLowerCase();return Ca(md,f)}if(!a.LanguageDef)throw"Type error: unexpected '"+a.constructor.name+"', expecting 'GenLanguageDef.LanguageDef'";var Da=Sa(F(db)),Ua=m(P(V(a.commentLine)))(ja,F(function(f){return f!="\n"}))(n,null),z=Na(H(a.commentEnd+a.commentStart)),tc=[k(P(V(a.commentEnd)),n(null)),"<|>",k(Sa(Ab(z)),d),"<|>",k(W(z),d),"<?>","end of comment"],uc=v(k(P(V(a.commentEnd)),
n(null)),"<|>",k(g,e),"<|>",k(Sa(Ab(z)),e),"<|>",k(W(z),e),"<?>","end of comment");z=a.nestedComments?uc:tc;var wb=k(P(V(a.commentStart)),z);z=cb(a.commentLine);var X=cb(a.commentStart),sc=(z&&X?[ja,[Da,"<?>",""]]:z?[ja,[Da,"<|>",wb,"<?>",""]]:X?[ja,[Da,"<|>",Ua,"<?>",""]]:[ja,[Da,"<|>",Ua,"<|>",wb,"<?>",""]]).resolve(),yb=b(";"),xb=b(",");Da=b(".");Ua=b(":");z=Ya("abfnrtv\\\"'","a\u0008\u000c\n\r\t\u000b\\\"'");X=Ya(["NUL","SOH","STX","ETX","EOT","ENQ","ACK","BEL","DLE","DC1","DC2","DC3","DC4","NAK",
"SYN","ETB","CAN","SUB","ESC","DEL"]+["BS","HT","LF","VT","FF","CR","SO","SI","EM","FS","GS","RS","US","SP"],["NUL","SOH","STX","ETX","EOT","ENQ","ACK","BEL","DLE","DC1","DC2","DC3","DC4","NAK","SYN","ETB","CAN","SUB","ESC","DEL"]+["BS","HT","LF","VT","FF","CR","SO","SI","EM","FS","GS","RS","US","SP"]);z=ia(G(S,z));var ea=ia(G(M,X));X=F(function(f){return f!='"'&&f!="\\"&&f>"\u0016"});var ta=s("&"),La=m(Ha,Bb)(s("\\"),"<?>","end of string gap"),ua=m("code","<-",N,"<|>",k(s("o"),J(8,Cb)),"<|>",k(s("x"),
J(16,Db)))(t(function(f){return toEnum(Ka(f.code))})),ka=m(s("^"))("code","<-",yc)(t(function(f){return toEnum(fromEnum(f.code)-fromEnum("A"))}));ea=v(z,"<|>",ua,"<|>",ea,"<|>",ka,"<?>","escape code");z=k(s("\\"),ea);ua=F(function(f){return f!="'"&&f!="\\"&&f>"\u0016"});z=v(ua,"<|>",z,"<?>","literal character");z=v(c,[qa,s("'"),[s("'"),"<?>","end of character"],z],"<?>","character");ta=m(s("\\"))(m(La)(n,R.Nothing),"<|>",m(ta)(n,R.Nothing),"<|>",m("esc","<-",ea)(O,R.Just,"esc"));X=v(m("c","<-",X)(O,
R.Just,"c"),"<|>",ta,"<?>","string character");X=v(c,[m("str","<-",qa,s('"'),[s('"'),"<?>","end of string"],[pa,X])(t,function(f){return ya(wa(Mb)(la,wa(I)),"",f.str)}),"<?>","literal string"]);var ra=J(10,Eb);ta=m(W,"xX")(J,16,Db);La=m(W,"oO")(J,8,Cb);var ld=v(m(s("."))("digits","<-",Ha,Eb,"<?>","fraction")(t,function(f){return ya(aa,0,f.digits)}),"<?>","fraction");ea=v([s("-"),">>",n,Qb],"<|>",[s("+"),">>",n,la],"<|>",n,la);var xc=v(m(W,"eE")("f","<-",ea)("e","<-",ra,"<?>","exponent")(O,ba,"f",
"e"),"<?>","exponent");ua=m("n","<-",ra)(function(f,l,x){return U(l.n)(f,l,x)});ka=m("n","<-",ra)(function(f,l,x){return Ra(Aa.Left(l.n),ga(l.n))(f,l,x)});var ma=v(m("n","<-",ta,"<|>",La)(O,Aa.Left,"n"),"<|>",ka,"<|>",ga(0),"<|>",n,Aa.Left(0));ka=v(k(s("0"),ma),"<|>",ka);ma=v(m(s,"0")(ta,"<|>",La,"<|>",ra,"<|>",n,0),"<?>","");ma=w(ma,ra);var Ma=m("f","<-",c,ea)("n","<-",ma)(t,function(f){return f.f(f.n)});ea=[c,ka,"<?>","number"].resolve();ua=[c,ua,"<?>","float"].resolve();ka=[c,Ma,"<?>","integer"].resolve();
ma=[c,ma,"<?>","natural"].resolve();Ma=v(m("c","<-",a.opStart)("cs","<-",pa,a.opLetter)(O,ab,"c","cs"),"<?>","operator");Ma=v(c,"$",P,"$",m("name","<-",Ma)(function(f,l,x){return(Q(l.name)?ib("reserved operator "+l.name):n(l.name))(f,l,x)}));var Fb=v(m("c","<-",a.identStart)("cs","<-",pa,a.identLetter)(O,ab,"c","cs"),"<?>","identifier");Fb=v(c,"$",P,"$",m("name","<-",Fb)(function(f,l,x){return(zb(l.name)?ib("reserved word "+l.name):n(l.name))(f,l,x)}));var zc=Za(a.reservedNames),md=a.caseSensitive?
zc:G(function(f){return f.toLowerCase()},zc);return ub.TokenParser(za,{identifier:Fb,reserved:da,operator:Ma,reservedOp:$,charLiteral:z,stringLiteral:X,natural:ma,integer:ka,float_:ua,naturalOrFloat:ea,decimal:ra,hexadecimal:ta,octal:La,symbol:b,lexeme:c,whiteSpace:sc,parens:h,braces:j,angles:i,brackets:o,squares:o,semi:yb,comma:xb,colon:Ua,dot:Da,semiSep:A,semiSep1:B,commaSep:p,commaSep1:u})}function Gb(){}function Ac(){}function nd(a,b){function c(h,j){return function(i,o,p){return h(o[j])(i,o,
p)}}function d(h,j){var i=h[0],o=j[0],p=j[1],A=j[2],u=j[3];j=j[4];if(h.Infix){var B=h[1];if(B.AssocNone)return[o,p,I(i,A),u,j];if(B.AssocLeft)return[o,I(i,p),A,u,j];if(B.AssocRight)return[I(i,o),p,A,u,j]}if(h.Prefix)return[o,p,A,I(i,u),j];if(h.Postfix)return[o,p,A,u,I(i,j)]}function e(h,j){return P(k(j,Bc("ambiguous use of a "+h+" associative operator")))}function g(h,j){function i(D){return v(m("f","<-",N)("y","<-",m("z","<-",Q)(c,o,"z"))(t,function(da){return da.f(D,da.y)}),"<|>",ga,"<|>",$)}function o(D){return w(i(D),
n(D))}function p(D){return v(m("f","<-",aa)("y","<-",Q)(function(da,Ca,zb){return A(Ca.f(D,Ca.y))(da,Ca,zb)}),"<|>",U,"<|>",$)}function A(D){return w(p(D),n(D))}function u(D){return m("f","<-",ba)("y","<-",Q)(U,"<|>",ga,"<|>",$,"<|>",t,function(da){return da.f(D,da.y)})}var B=ya(d,[[],[],[],[],[]],j),S=B[1],M=B[2],J=B[3];j=B[4];var N=ia(B[0]),aa=ia(S),ba=ia(M);B=sa(ia(J),"");j=sa(ia(j),"");var U=e("right",N),ga=e("left",aa),$=e("non",ba);j=w(j,n(la));B=w(B,n(la));var Q=m("pre","<-",B)("x","<-",h)("post",
"<-",j)(t,function(D){return D.post(D.pre(D.x))});return m("x","<-",Q)(c,i,"x","<|>",c,p,"x","<|>",c,u,"x","<|>",t,"x","<?>","operator").resolve()}return Wa(g,b,a)}var y,Fc={}.toString,Gc=[].slice,la=function(a){return a},T=wa(function(a,b){return a(b)}),vc=parseInt,Ka=la,wc=la,L=String.fromCharCode,Y=Math.round,na=window.JSParsec={};C(na,{curry:wa,const_:Jb,isArray:xa,isDefined:Va,slice:H,foldl:Wa,foldr:ya,map:G,filter:Kb,indexOf:Xa,lastIndexOf:Lb,zip:Ya,sort:Za,nub:Na,maybe:Mb,compare:Nb,compose:Ob,
compose1:Pb,call:T,id:la,flip:$a,cons:I,consJoin:ab,replicate:bb,negate:Qb,null_:cb,elem:Oa,isSpace:db,isUpper:Rb,isLower:Sb,isAlpha:eb,isAlphaNum:Tb,isDigit:Ub,isHexDigit:Vb,isOctDigit:Wb,digitToInt:fb,range:Hc,extend:C,namespace:Oc,toInteger:vc,fromInteger:Ka,fromIntegral:wc,fst:Ic,snd:Jc,uncurry:Kc,lookup:Lc,readHex:Mc,readOct:Nc,chr:L,round:Y});var za=new Xb;Pa.prototype.toString=Yb();Pa.prototype.dataConstructorToString=Yb(true);fa(R,[["Just","a"],"Nothing"]);fa(Ea,["LT","EQ","GT"]);fa(Aa,[["Left",
"a"],["Right","b"]]);var Ba={$:{func:T,fixity:oa(0)},".":{func:Pb,fixity:oa(9)},":":{func:I,fixity:oa(5)}};Array.prototype.resolve=function(){return ha(this)};L=new hb;C(na,{data:fa,ADT:Pa,record:za,Maybe:R,Ordering:Ea,Either:Aa,operators:Ba,infix:Zb,infixl:ca,infixr:oa,arr:Sc,op:Uc,str:Tc,ex:v,resolve:ha,recurse:L,Recurse:hb,cs:m});Fa.prototype={memoize:false,scrollTo:function(a){this.index=a;this.length=this.input.length-a;return this},scroll:function(a){this.index+=a;this.length-=a;return this},
at:function(a){return this.input.charAt(this.index+a)},substring:function(a,b){return this.input.substring(a+this.index,(b||this.length)+this.index)},substr:function(a,b){return this.input.substring(a+this.index,b||this.length)},toString:function(){var a=this.substring(0);return"PS at "+this.index+" "+(a.length?'"'+a+'"':"Empty")},getCached:function(a){if(this.memoize)if(a=this.cache[a])if(a=a[this.index]){this.index=a.index;this.length=a.length;return a}},putCached:function(a,b,c){if(!this.memoize)return false;
c.index=this.index;c.length=this.length;var d=this.cache[a];d||(d=this.cache[a]={});d[b]=c},sourceLine:function(a){return(a=this.input.substring(0,a).match(/(\r\n)|\r|\n/g))?a.length:0}};var Yc=E(y),Bc=ac,rb=bc;L=rb;var kc=0,Hb=function(a,b){function c(d,e,g){return{func:a,args:[d,e,function(h){return h.success?b(d,e,g):g(h)}]}}c.constructor=r;return c},k=function(){function a(c,d,e){var g={},h=1,j=b.length,i=b[0];for(g.scope=d;h<j;++h)i=Hb(i,b[h]);return i(c,g,e)}var b=G(jb,arguments);a.constructor=
r;return a},O=Ob(t,nb),qc=cc,rc=dc,n=ec,Cc=n;Y=ob;var va=Hb,Z=w,pa=jc(false),Ha=jc(true),P=Qa(function(a,b,c,d){b=C({},b);if(b.success)return b;c.scrollTo(d);b.ast=y;return b}),ja=function(a){return Qa(function(b,c){c=C({},c);c.ast=y;return c})(pa(a),null)},s=qb(function(a,b){if(b.length>0&&b.at(0)==a){b.scroll(1);return E(a)}return Ga(a)}),F=qb(function(a,b){var c=b.at(0);if(b.length>0&&a(c)){b.scroll(1);return E(c)}return Ga(c)}),V=function(a){return Qa(function(b,c,d,e){c=C({},c);c.ast=c.ast.join("");
if(c.success)delete c.expecting;else c.expecting={at:e,expecting:a};if(!c.ast.length)c.ast=y;return c})(ic(G(s,a)),null)},sa=Qa(function(a,b,c,d){if(!b.success){b=C({},b);b.expecting={at:d,expecting:a}}return b}),Ib=qb(function(a,b){var c;if(typeof a=="string")if(b.substring(0,a.length)==a){b.scroll(a.length);c=E(a)}else c=Ga(a);else if(a.exec){var d=new RegExp("^"+a.source);c=b.substring(0);d=(d=(d=d.exec(c))&&d[0])&&d.length;c=c.substr(0,d);if(d){b.scroll(d);c=E(c)}else c=Ga(a.source)}return c});
C(Ba,{"<-":{func:q,fixity:oa(-1)},">>=":{func:mb,fixity:ca(1)},"=<<":{func:$a(mb),fixity:oa(1)},">>":{func:va,fixity:ca(1)},"*>":{func:va,fixity:ca(4)},"<*":{func:hc,fixity:ca(4)},"<$>":{func:Y,fixity:ca(4)},"<*>":{func:fc,fixity:ca(4)},"<**>":{func:wa(pb)($a(T)),fixity:ca(4)},"<$":{func:function(a,b){return hc(Cc(value),b)},fixity:ca(4)},"<|>":{func:w,fixity:oa(1)},"<?>":{func:sa,fixity:Zb(0)}});C(na,{sequence:lc,run:Xc,Parser:r,ParseState:Fa,ps:$b,toParser:jb,unexpected:ib,parsecMap:Y,fmap:Y,liftM:ob,
liftM2:pb,liftM3:gc,liftA:Y,liftA2:pb,liftA3:gc,ap:fc,parserBind:mb,parserReturn:ec,return_:n,pure:Cc,parserFail:ac,fail:Bc,parserZero:bc,mzero:rb,empty:L,parserPlus:w,parserPlusN:Zc,mplus:Z,do_:k,do2:Hb,bind:q,ret:t,withBound:nb,returnCall:O,lazy:$c,getPosition:cc,setPosition:dc,getParserState:qc,setParserState:rc,tokens:ic,many:pa,many1:Ha,string:V,char_:s,satisfy:F,label:sa,try_:P,skipMany:ja,match:Ib});var W=function(a){return sa(F(function(b){return Oa(b,a)}),"oneOf("+a+")")},Ab=function(a){return sa(F(function(b){return!Oa(b,
a)}),"noneOf("+a+")")},Bb=[F,db,"<?>","space"].resolve();Y=[ja,Bb,"<?>","white space"].resolve();va=[s,"\n","<?>","new-line"].resolve();Z=[s,"\t","<?>","tab"].resolve();var yc=[F,Rb,"<?>","uppercase letter"].resolve();Ib=[F,Sb,"<?>","lowercase letter"].resolve();T=[F,Tb,"<?>","letter or digit"].resolve();L=[F,eb,"<?>","letter"].resolve();var Eb=[F,Ub,"<?>","digit"].resolve(),Db=[F,Vb,"<?>","hexadecimal digit"].resolve(),Cb=[F,Wb,"<?>","octal digit"].resolve(),od=[F,Jb(true)].resolve();C(na,{oneOf:W,
noneOf:Ab,space:Bb,spaces:Y,newline:va,tab:Z,upper:yc,lower:Ib,alphaNum:T,letter:L,digit:Eb,hexDigit:Db,octDigit:Cb,anyChar:od});var qa=wa(function(a,b,c){return k(a,q("x",c),b,t("x"))});C(na,{choice:ia,count:ed,between:qa,option:Ra,optionMaybe:ad,optional:bd,skipMany1:Sa,sepBy:sb,sepBy1:Ta,endBy:dd,endBy1:cd,sepEndBy:nc,sepEndBy1:mc,chainl:gd,chainl1:pc,chainr:fd,chainr1:oc,eof:id,notFollowedBy:tb,manyTill:jd,lookAhead:kd,anyToken:hd});fa(Ia,[["LanguageDef",{commentStart:String,commentEnd:String,
commentLine:String,nestedComments:Boolean,identStart:r,identLetter:r,opStart:r,opLetter:r,reservedNames:Array,reservedOpNames:Array,caseSensitive:Boolean}]]);fa(ub,[["TokenParser",{identifier:r,reserved:Function,operator:r,reservedOp:Function,charLiteral:r,stringLiteral:r,natural:r,integer:r,float_:r,naturalOrFloat:r,decimal:r,hexadecimal:r,octal:r,symbol:Function,lexeme:Function,whiteSpace:r,parens:Function,braces:Function,angles:Function,brackets:Function,squares:Function,semi:r,comma:r,colon:r,
dot:r,semiSep:Function,semiSep1:Function,commaSep:Function,commaSep1:Function}]]);C(na,{GenLanguageDef:Ia,GenTokenParser:ub,makeTokenParser:vb});Z=W(":!#$%&*+./<=>?@\\^|-~");Y=Ia.LanguageDef(za,{commentStart:"",commentEnd:"",commentLine:"",nestedComments:true,identStart:[L,"<|>",s("_")].resolve(),identLetter:[T,"<|>",W("_'")].resolve(),opStart:Z,opLetter:Z,reservedOpNames:[],reservedNames:[],caseSensitive:true});va=Ia.LanguageDef(za,{commentStart:"{-",commentEnd:"-}",commentLine:"--",nestedComments:true,
identStart:L,identLetter:[T,"<|>",W,"_'"].resolve(),opStart:Z,opLetter:Z,reservedOpNames:[],reservedNames:[],caseSensitive:true});T=Ia.LanguageDef(za,{commentStart:"/*",commentEnd:"*/",commentLine:"//",nestedComments:true,identStart:L,identLetter:[T,"<|>",W,"_'"].resolve(),opStart:Z,opLetter:Z,reservedOpNames:[],reservedNames:[],caseSensitive:false});L=va.update({reservedOpNames:["::","..","=","\\","|","<-","->","@","~","=>"],reservedNames:["let","in","case","of","if","then","else","data","type",
"class","default","deriving","do","import","infix","infixl","infixr","instance","module","newtype","where","primitive"]});var Dc=L.update({identLetter:[L.identLetter,"<|>",s("#")].resolve(),reservedNames:L.reservedNames.concat(["foreign","import","export","primitive","_ccall_","_casm_","forall"])}),Ec=T.update({reservedNames:["case","class","default","extends","import","in","let","new","of","package"],caseSensitive:true});C(na,{emptyDef:Y,haskellStyle:va,javaStyle:T,haskellDef:Dc,mondrianDef:Ec,getHaskell:function(){return vb(Dc)},
getMondrian:function(){return vb(Ec)}});fa(Gb,["AssocNone","AssocLeft","AssocRight"]);fa(Ac,[["Infix",r,Gb],["Prefix",r],["Postfix",r]]);C(na,{Assoc:Gb,Operator:Ac,buildExpressionParser:nd})})();
