/*

 JSParsec - A parser combinator library for JavaScript

 Version: 1.0.1

 http://code.google.com/p/jsparsec/

 Copyright (c) 2010 Balazs Endresz (balazs.endresz@gmail.com)
 Dual licensed under the MIT and GPL licenses.


 The initial implementation of some combinators and the memoization is derived from:
 http://www.bluishcoder.co.nz/2007/10/javascript-parser-combinators.html

 Most functions should behave like their counterparts in Parsec:
 http://www.haskell.org/haskellwiki/Parsec

*/
(function(){function Ea(a){function b(){var c=E(arguments);return c.length>=(a._length===y?a.length:a._length)?a.apply(null,c):function(){return b.apply(null,c.concat(E(arguments)))}}return b}function Jb(a){return function(){return a}}function wa(a){return Fc.call(a)=="[object Array]"}function Xa(a){return a!==y}function E(a,b){return Gc.call(a,b||0)}function Ya(a,b,c){for(var d=0,e=c.length;d<e;++d)b=a(b,c[d]);return b}function xa(a,b,c){for(var d=c.length-1;d>-1;--d)b=a(c[d],b);return b}function G(a,
b){for(var c=[],d=0,e=b.length;d<e;++d)c[d]=a(b[d],d);return c}function Kb(a,b){for(var c=[],d=0,e=a.length;d<e;++d)b(a[d])&&c.push(a[d]);return c}function Za(a,b){var c=a.length;if(!c)return-1;for(var d=0;d<c;d++)if(a[d]===b)return d;return-1}function Lb(a,b){var c=a.length;if(!c)return-1;for(c=c-1;c>-1;--c)if(a[c]===b)return c;return-1}function $a(a,b){for(var c=[],d=0,e=Math.min(a.length,b.length);d<e;++d)c[d]=[a[d],b[d]];return c}function ab(a){if(a.sort)return a.sort();return E(a).sort().join("")}
function Oa(a,b){b=b===y?[]:b;var c=a[0],d=E(a,1);return!a.length?[]:Pa(c,b)?Oa(d,b):H(c,Oa(d,H(c,b)))}function Mb(a,b,c){if(c.Nothing)return a;if(c.Just)return b(c[0])}function Nb(a,b){return a===b?Fa.EQ:a<=b?Fa.LT:Fa.GT}function C(a,b){for(var c in b)a[c]=b[c];return a}function Ob(a,b){return function(){return a(b.apply(null,arguments))}}function Pb(a,b){return function(c){var d=E(arguments,1);d.unshift(b(c));return a.apply(null,d)}}function bb(a){return function(b,c){return a(c,b)}}function H(a,
b){if(typeof a=="string"&&typeof b=="string")return a+b;return[a].concat(b)}function cb(a,b){if(typeof a=="string"&&typeof b=="string")return a+b;return a+b.join("")}function db(a,b){for(var c=[],d=0;d<a;++d)c[d]=b;return c}function Qb(a){return-a}function eb(a){return!a.length}function Pa(a,b){return(b.indexOf?b.indexOf(a):Za(b,a))!=-1}function fb(a){return/^\s$/.test(a)}function Rb(a){return a.toUpperCase()==a}function Sb(a){return a.toLowerCase()==a}function Tb(a){return/^\w$/.test(a)}function gb(a){return/^\w$/.test(a)&&
/^\D$/.test(a)}function Ub(a){return/^\d$/.test(a)}function Vb(a){return/^[0-9A-Fa-f]$/.test(a)}function Wb(a){return/^[0-7]$/.test(a)}function hb(a){return parseInt(a,16)}function Hc(a,b){return{indexOf:function(c){return c>=a&&c<=b?true:-1},toString:function(){return"range("+a+", "+b+")"}}}function Ic(a){return a[0]}function Jc(a){return a[1]}function Kc(a){return function(b){return a(b[0],b[1])}}function Lc(a,b){var c=b.length;if(!c)return R.Nothing;for(var d=0;d<c;++d)if(b[d][0]===a)return R.Just(b[d][1]);
return R.Nothing}function Mc(a){return parseInt(a.join?a.join(""):a,16)}function Nc(a){return parseInt(a.join?a.join(""):a,8)}function Oc(){var a,b;G(function(c){b=c.split(".");a=window[b[0]]=window[b[0]]||{};G(function(d){a=a[d]=a[d]||{}},b.slice(1))},arguments);return a}function Xb(){}function Pc(a,b){if(!/^[0-9]$/.test(b))return b;if(typeof a!="object")return b;var c=0;for(var d in a){if(a.hasOwnProperty(d)&&c==b)return d;c++}return-1}function Qa(){}function Yb(a){return function(){var b=[],c=
this._recordset;if(c&&!wa(c)){for(var d in c){var e=a?c[d].name||c[d]:this[d];if(!a&&e instanceof Function)e=e.constructor!=Function?e.constructor.name:"Function("+e.name+")";b.push(d+" :: "+e)}c=db(this._dataConstructor.length+2," ").join("");b="{"+b.join("\n"+c+",")+"\n"+c+"}"}else{for(d=0;d in this;d++)b.push(a?c[d].name||c[d]:this[d]);b=b.join(" ")}return"("+this._dataConstructor+(b?" ":"")+b+")"}}function fa(a,b){function c(j,i){function o(A,v){var B=A instanceof Xb,S=B?v:E(arguments),M=new a,
I=0;M.constructor=a;M._recordset=p&&i[0]||i;M._dataConstructor=j;M.update=function(ga){var $={};for(var Q in i[0]){$[Q]=this[Q];if(Q in ga)$[Q]=ga[Q]}return o(ya,$)};M[j]=true;if(S!==y)for(var N in S)if(S.hasOwnProperty(N)&&N!=j){if(B&&i&&p)if(!(N in i[0]))throw"The accessor '"+N+"' is not defined for the data constructor '"+j+"'";var aa=Pc(i[0],N),ba=S[I]!==undefined?S[I]:S[aa],U=p?i[0][aa]:i[I];if(U.name&&!(U==ba.constructor||ba instanceof U))throw"Type error: expecting '"+U.name+"' instead of '"+
ba.constructor.name+"' in the argument '"+(aa||I)+"' of the data constructor '"+j+"' of type '"+a.name+"'";M[aa]=M[I]=M[N]=S[N];I++}else if(N==j)throw"Accessor has the same name as the data constructor: '"+j+"'";return M}var p=i&&typeof i[0]=="object";return o}if(a.constructors)throw"Type constructor has been already defined: '"+a.name+"'";a.constructors=b;a.prototype=new Qa;for(var d=0,e=b.length;d<e;++d){var h=typeof b[d]!="object",g=h?b[d]:b[d][0];if(g in a)throw"The name of the data constructor ("+
g+") is invalid!";a[g]=h?c(g)():c(g,E(b[d],1));if(!h)a[g]._length=E(b[d],1).length}}function R(){}function Fa(){}function za(){}function ca(a){return["l",a]}function oa(a){return["r",a]}function Zb(a){return["x",a]}function Qc(a){if(a)if(!a._String){var b=Aa[a];if(a._Op&&!b)return"l";return b&&(b.fixity[0]||"l")}}function Rc(a){if(a)if(!a._String){var b=Aa[a];if(a._Op&&!b)return 9;return b&&(Xa(b.fixity[1])?b.fixity[1]:9)}}function ib(a,b,c){var d;if(a[b]._Op){delete a[b]._Op;d=a[b]}else d=Aa[a[b]].func;
d=d(a[b-1],a[b+1]);a.splice(b-1,3,d);return ha(a,c)}function Sc(a){a._Array=true;return a}function Tc(a){a=new String(a);a._String=true;return a}function Uc(a){a._Op=true;return a}function ha(a,b){a=G(function(i){if(i&&i._Array){delete i._Array;return i}return wa(i)?ha(i,b):i&&i.CallStream?i.resolve(b):i},a);if(b)a=G(function(i){return i instanceof jb?b:i},a);for(var c=[],d=[],e=0,h=a.length;e<h;++e){var g=a[e],j=false;if(Aa[g])j=true;if(g&&g._String){j=false;g=g.toString()}if(g&&g._Op)j=true;if(!j&&
e!=h-1)c.push(g);else{e==h-1&&c.push(g);c=c.length>1?c[0].apply(null,c.slice(1)):c[0];d.push(c);e!=h-1&&d.push(g);c=[]}}a=d;d=G(Qc,a);h=G(Rc,a);g=Kb(h,Xa).sort().pop();e=Za(h,g);h=Lb(h,g);return d[e]=="l"?ib(a,e,b):d[h]=="r"?ib(a,h,b):d[e]=="x"?ib(a,e,b):a[0]}function u(){function a(){return d.apply(null,arguments)}function b(){return(e?d:b.resolve()).apply(null,arguments)}var c=arguments,d,e;b.resolve=function(h){if(e)return d;d=ha(c,h||a);c=null;e=true;return d};b.CallStream=true;b.constructor=
q;return b}function jb(){}function n(){function a(h,g,j){return d(h,g,j)}function b(h,g,j){if(e||h instanceof Ga)return(e?d:b.resolve())(h,g,j);c.push(ha(arguments,a));return b}var c=[],d,e;c.push(ha(arguments,a));b.resolve=function(){if(e)return d;d=k.apply(null,c);e=true;c=null;return d};b.CallStream=true;b.constructor=q;return b}function Ga(a,b){this.input=a;this.index=b||0;this.length=a.length-this.index;this.cache={};return this}function $b(a){return new Ga(a)}function J(a,b,c){return{ast:a,
success:b===y?true:b,expecting:c}}function Ha(a){return J(y,false,a)}function Ra(a){return function(b,c,d){return d(J(null,false,{unexpected:a}))}}function ac(a){return function(b,c,d){return d(J(y,false,a))}}function bc(a,b,c){return c(J(y,false))}function kb(a){return typeof a=="string"?V(a):wa(a)?ha(a):a}function Vc(a){for(;a&&a.func;)a=a.func.apply(null,a.args||[])}function lb(a,b){b=b||0;b++;if(a&&a.func){a=a.func.apply(null,a.args||[]);b%500==0?setTimeout(function(){lb(a,b)},1):lb(a,b)}else b=
0}function Wc(a,b,c,d,e){var h=b instanceof Ga?b:$b(b);(e?lb:Vc)({func:a,args:[h,{},function(g){g.state=h;delete g.index;delete g.length;if(g.success){delete g.error;delete g.expecting}else{g.error=mb(g.expecting,g.state);d&&d(g.error)}c(g)}]})}function mb(a,b,c,d){c=c===undefined?b.index:c;if(typeof a=="string"){var e=b.input.split("\n"),h=e.length,g=b.input.substr(c).split("\n").length;h=h-g+1;e=c-e.splice(0,h-1).join("\n").length;b=d||b.input.substr(c,a.length).substr(0,6);return'Unexpected "'+
(b.length?b:"end of input")+(d?"":'", expecting "'+a)+'" at line '+h+" char "+e}if(wa(a)){a=G(function(j){return typeof j=="object"?j.expecting:j},a);return mb(a.join('" or "'),b)}else if(typeof a=="object")return mb(a.expecting,b,a.at,a.unexpected)}function q(){}function Ba(a,b){return function(c,d,e){return{func:a,args:[c,d,function(h){return h.success?{func:b(h.ast),args:[c,d,e]}:e(h)}]}}}function r(a,b){if(a=="scope")throw"Can't use 'scope' as an identifier!";return function(c,d,e){return{func:b,
args:[c,d,function(h){if(h.success)d[a]=h.ast;h=C({},h);return e(h)}]}}}function t(a,b){b&&E(arguments);return function(c,d,e){return{func:function(){var h;if(typeof a=="string"){if(!(a in d))throw'Not in scope: "'+a+'"';h=d[a]}else h=a(d);return e(J(h))}}}}function nb(a){var b=E(arguments,1);return function(c){return a.apply(null,G(function(d){return c[d]},b))}}function cc(a,b,c){return c(J(a.index))}function dc(a){var b=typeof a;return function(c,d,e){c.scrollTo(b=="string"?d[a]:a);return e(Xc)}}
function ec(a){return function(b,c,d){return d(J(a))}}function fc(a,b){return k(r("a",a),r("b",b),t(function(c){return c.a(c.b)}))}function ob(a,b){return k(r("x1",b),O(a,"x1"))}function pb(a,b,c){return k(r("x1",b),r("x2",c),O(a,"x1","x2"))}function gc(a,b,c,d){return k(r("x1",b),r("x2",c),r("x3",d),O(a,"x1","x2","x3"))}function hc(a,b){return k(r("a",a),b,t("a"))}function w(a,b){function c(d,e,h){return{func:a,args:[d,e,function(g){function j(o){var p=o.expecting;if(p)if(wa(p))i=i.concat(p);else i.push(p);
if(o.success)delete o.expecting;else o.expecting=i}var i=[];j(g);return g.ast!==y?{func:h,args:[g]}:{func:b,args:[d,e,function(o){j(o);return h(o)}]}}]}}c.constructor=q;return c}function Yc(){var a=G(kb,arguments);return function(b,c,d){for(var e=1,h=a.length,g=a[0];e<h;++e)g=w(g,a[e]);return g(b,c,d)}}function ic(a){return function(b,c,d){function e(i){return function(o,p,A){return{func:i,args:[o,p,function(v){h++;if(!v.success)return A(v);v.ast!==y&&g.push(v.ast);return h<j?e(a[h])(o,p,A):A(v)}]}}}
var h=0,g=[],j=a.length;return{func:e(a[h]),args:[b,c,function(i){i=C({},i);i.ast=g;i.success&&delete i.expecting;return d(i)}]}}}function jc(a){return function(b){return function(c,d,e){function h(i){return function(o,p,A){return{func:i,args:[o,p,function(v){if(!v.success)return A(v);g=true;v.ast!==y&&j.push(v.ast);return h(i)(o,p,A)}]}}}var g=false,j=[];return{func:h(b),args:[c,d,function(i){i=C({},i);i.success=!a||g&&a;i.ast=j;if(i.success)delete i.expecting;else i.ast=y;return e(i)}]}}}}function qb(a){return function(b){var c=
kc++,d=function(e,h,g){h=e.index;var j=e.getCached(c);if(j!==y)return g(j);j=a(b,e,h);e.putCached(c,h,j);return g(j)};d.constructor=q;return d}}function Sa(a){return function(b,c){var d=kc++,e=function(h,g,j){var i=h.index,o=h.getCached(d);if(o!==y)return j(o);return{func:b,args:[h,g,function(p){p=a(c,p,h,i);h.putCached(d,i,p);return j(p)}]}};e.constructor=q;return e}}function lc(a){function b(c,d){return k(r("x",c),r("xs",d),t(nb(H,"x","xs")))}return xa(b,m([]),a)}function Zc(a){return function(b,
c,d){return a(c)(b,c,d)}}function ia(a){return xa(w,rb,a)}function Ta(a,b){return w(b,m(a))}function $c(a){return Ta(R.Nothing,ob(R.Just,a))}function ad(a){return w(k(a,m(null)),m(null))}function pa(a,b,c){return k(a,r("x",c),b,t("x"))}function Ua(a){return k(a,ja(a))}function sb(a,b){return w(Va(a,b),m([]))}function Va(a,b){return k(r("x",a),r("xs",qa(k(b,a))),O(H,"x","xs"))}function mc(a,b){return k(r("x",a),w(k(b,r("xs",function(c,d,e){return nc(a,b)(c,d,e)}),t(function(c){return H(c.scope.x,c.xs)})),
t(function(c){return[c.x]})))}function nc(a,b){return w(mc(a,b),m([]))}function bd(a,b){return Ia(k(r("x",a),b,t("x")))}function cd(a,b){return qa(k(r("x",a),b,t("x")))}function dd(a,b){return a<=0?m([]):lc(db(a,b))}function ed(a,b,c){return w(oc(a,b),m(c))}function fd(a,b,c){return w(pc(a,b),m(c))}function pc(a,b){function c(d){var e=k(r("f",b),r("y",a),function(h,g,j){return c(g.f(d,g.y))(h,g,j)});return w(e,m(d))}return Ba(a,c)}function oc(a,b){function c(e){var h=k(r("f",b),r("y",d),t(function(g){return g.f(e,
g.y)}));return w(h,m(e))}var d=Ba(a,c);return d}function gd(a,b,c){b=a.at(0);if(b.length){a.scroll(1);return c(J(b))}return c(Ha("anyToken"))}function hd(a,b,c){return c(J(y,!a.length,a.length?"end of input":y))}function tb(a){return P(w(Ba(P(a),Ra),m(null)))}function id(a,b){function c(e,h,g){return d(e,h,g)}var d=w(k(b,m([])),k(r("x",a),r("xs",c),O(H,"x","xs")));return d}function jd(a){return k(r("state",qc),r("x",a),rc("state"),t("x"))}function Ja(){}function ub(){}function vb(a){function b(f){return c(V(f))}
function c(f){return k(r("x",f),sc,t("x"))}function d(f,l,x){return tc(f,l,x)}function e(f,l,x){return uc(f,l,x)}function h(f,l,x){return wb(f,l,x)}function g(f){return pa(b("("),b(")"),f)}function j(f){return pa(b("{"),b("}"),f)}function i(f){return pa(b("<"),b(">"),f)}function o(f){return pa(b("["),b("]"),f)}function p(f){return sb(f,xb)}function A(f){return sb(f,yb)}function v(f){return Va(f,xb)}function B(f){return Va(f,yb)}function S(f){return k(s(f[0]),m(f[1]))}function M(f){return P(k(V(f[0]),
m(f[1])))}function I(f,l){return n("digits","<-",Ia,l)(t,function(x){return Ya(function(K,Ka){return f*K+vc(hb(Ka))},0,x.digits)})}function N(f,l,x){return ra(f,l,x)}function aa(f,l){return(l+wc(hb(f)))/10}function ba(f){return f<0?1/ba(-f):La(Math.pow(10,f))}function U(f){return u(n("fract","<-",kd)("expo","<-",Ta,1,xc)(t,function(l){return La(f+l.fract)*l.expo}),"<|>",n("expo","<-",xc)(t,function(l){return La(f)*l.expo}))}function ga(f){return n("f","<-",U,f)(O,za.Right,"f")}function $(f){return u(c,
"$",P,n(V(f))(tb,a.opLetter,"<?>","end of "+f))}function Q(f){return Ca(ab(a.reservedOpNames),f)}function D(f){function l(K){return!K.length?m(null):k(sa(x(K[0]),""+f),l(E(K,1)))}function x(K){return gb(K)?w(s(K.toLowerCase()),s(K.toUpperCase())):s(K)}return a.caseSensitive?V(f):k(l(f),m(f))}function da(f){return u(c,"$",P,n(D(f))(tb,a.identLetter,"<?>","end of "+f))}function Ca(f,l){function x(K){if(!K.length)return false;var Ka=Nb(K[0],l);return Ka.LT?x(E(K,1)):Ka.EQ?true:Ka.GT?false:null}return x(f)}
function zb(f){f=a.caseSensitive?f:f.toLowerCase();return Ca(ld,f)}if(!a.LanguageDef)throw"Type error: unexpected '"+a.constructor.name+"', expecting 'GenLanguageDef.LanguageDef'";var Da=Ua(F(fb)),Wa=n(P(V(a.commentLine)))(ja,F(function(f){return f!="\n"}))(m,null),z=Oa(E(a.commentEnd+a.commentStart)),tc=u(k(P(V(a.commentEnd)),m(null)),"<|>",k(Ua(Ab(z)),d),"<|>",k(W(z),d),"<?>","end of comment"),uc=u(k(P(V(a.commentEnd)),m(null)),"<|>",k(h,e),"<|>",k(Ua(Ab(z)),e),"<|>",k(W(z),e),"<?>","end of comment");
z=a.nestedComments?uc:tc;var wb=k(P(V(a.commentStart)),z);z=eb(a.commentLine);var X=eb(a.commentStart),sc=(z&&X?[ja,[Da,"<?>",""]]:z?[ja,[Da,"<|>",wb,"<?>",""]]:X?[ja,[Da,"<|>",Wa,"<?>",""]]:[ja,[Da,"<|>",Wa,"<|>",wb,"<?>",""]]).resolve(),yb=b(";"),xb=b(",");Da=b(".");Wa=b(":");z=$a(E("abfnrtv\\\"'"),E("a\u0008\u000c\n\r\t\u000b\\\"'"));X=$a(["NUL","SOH","STX","ETX","EOT","ENQ","ACK","BEL","DLE","DC1","DC2","DC3","DC4","NAK","SYN","ETB","CAN","SUB","ESC","DEL"].concat(["BS","HT","LF","VT","FF","CR",
"SO","SI","EM","FS","GS","RS","US","SP"]),["NUL","SOH","STX","ETX","EOT","ENQ","ACK","BEL","DLE","DC1","DC2","DC3","DC4","NAK","SYN","ETB","CAN","SUB","ESC","DEL"].concat(["BS","HT","LF","VT","FF","CR","SO","SI","EM","FS","GS","RS","US","SP"]));z=ia(G(S,z));var ea=ia(G(M,X));X=F(function(f){return f!='"'&&f!="\\"&&f>"\u0016"});var ta=s("&"),Ma=n(Ia,Bb)(s("\\"),"<?>","end of string gap"),ua=n("code","<-",N,"<|>",k(s("o"),I(8,Cb)),"<|>",k(s("x"),I(16,Db)))(t(function(f){return toEnum(La(f.code))})),
ka=n(s("^"))("code","<-",yc)(t(function(f){return toEnum(fromEnum(f.code)-fromEnum("A"))}));ea=u(z,"<|>",ua,"<|>",ea,"<|>",ka,"<?>","escape code");z=k(s("\\"),ea);ua=F(function(f){return f!="'"&&f!="\\"&&f>"\u0016"});z=u(ua,"<|>",z,"<?>","literal character");z=u(c,[pa,s("'"),[s("'"),"<?>","end of character"],z],"<?>","character");ta=n(s("\\"))(k(Ma,m(R.Nothing)),"<|>",k(ta,m(R.Nothing)),"<|>",n("esc","<-",ea)(O,R.Just,"esc"));X=u(n("c","<-",X)(O,R.Just,"c"),"<|>",ta,"<?>","string character");X=u(c,
[n("str","<-",pa,s('"'),[s('"'),"<?>","end of string"],[qa,X])(t,function(f){return xa(Ea(Mb)(la,Ea(H)),"",f.str)}),"<?>","literal string"]);var ra=I(10,Eb);ta=n(W,"xX")(I,16,Db);Ma=n(W,"oO")(I,8,Cb);var kd=u(n(s("."))("digits","<-",Ia,Eb,"<?>","fraction")(t,function(f){return xa(aa,0,f.digits)}),"<?>","fraction");ea=u([s("-"),">>",m,Qb],"<|>",[s("+"),">>",m,la],"<|>",m,la);var xc=u(n(W,"eE")("f","<-",ea)("e","<-",ra,"<?>","exponent")(O,ba,"f","e"),"<?>","exponent");ua=n("n","<-",ra)(function(f,l,
x){return U(l.n)(f,l,x)});ka=n("n","<-",ra)(function(f,l,x){return Ta(za.Left(l.n),ga(l.n))(f,l,x)});var ma=u(n("n","<-",ta,"<|>",Ma)(O,za.Left,"n"),"<|>",ka,"<|>",ga(0),"<|>",m,za.Left(0));ka=u(k(s("0"),ma),"<|>",ka);ma=u(n(s,"0")(ta,"<|>",Ma,"<|>",ra,"<|>",m,0),"<?>","");ma=w(ma,ra);var Na=n("f","<-",c,ea)("n","<-",ma)(t,function(f){return f.f(f.n)});ea=[c,ka,"<?>","number"].resolve();ua=[c,ua,"<?>","float"].resolve();ka=[c,Na,"<?>","integer"].resolve();ma=[c,ma,"<?>","natural"].resolve();Na=u(n("c",
"<-",a.opStart)("cs","<-",qa,a.opLetter)(O,cb,"c","cs"),"<?>","operator");Na=u(c,"$",P,n("name","<-",Na)(function(f,l,x){return(Q(l.name)?Ra("reserved operator "+l.name):m(l.name))(f,l,x)}));var Fb=u(n("c","<-",a.identStart)("cs","<-",qa,a.identLetter)(O,cb,"c","cs"),"<?>","identifier");Fb=u(c,"$",P,n("name","<-",Fb)(function(f,l,x){return(zb(l.name)?Ra("reserved word "+l.name):m(l.name))(f,l,x)}));var zc=ab(a.reservedNames),ld=a.caseSensitive?zc:G(function(f){return f.toLowerCase()},zc);return ub.TokenParser(ya,
{identifier:Fb,reserved:da,operator:Na,reservedOp:$,charLiteral:z,stringLiteral:X,natural:ma,integer:ka,float_:ua,naturalOrFloat:ea,decimal:ra,hexadecimal:ta,octal:Ma,symbol:b,lexeme:c,whiteSpace:sc,parens:g,braces:j,angles:i,brackets:o,squares:o,semi:yb,comma:xb,colon:Wa,dot:Da,semiSep:A,semiSep1:B,commaSep:p,commaSep1:v})}function Gb(){}function Ac(){}function md(a,b){function c(g,j){return function(i,o,p){return g(o[j])(i,o,p)}}function d(g,j){var i=g[0],o=j[0],p=j[1],A=j[2],v=j[3];j=j[4];if(g.Infix){var B=
g[1];if(B.AssocNone)return[o,p,H(i,A),v,j];if(B.AssocLeft)return[o,H(i,p),A,v,j];if(B.AssocRight)return[H(i,o),p,A,v,j]}if(g.Prefix)return[o,p,A,H(i,v),j];if(g.Postfix)return[o,p,A,v,H(i,j)]}function e(g,j){return P(k(j,Bc("ambiguous use of a "+g+" associative operator")))}function h(g,j){function i(D){return u(n("f","<-",N)("y","<-",n("z","<-",Q)(c,o,"z"))(t,function(da){return da.f(D,da.y)}),"<|>",ga,"<|>",$)}function o(D){return w(i(D),m(D))}function p(D){return u(n("f","<-",aa)("y","<-",Q)(function(da,
Ca,zb){return A(Ca.f(D,Ca.y))(da,Ca,zb)}),"<|>",U,"<|>",$)}function A(D){return w(p(D),m(D))}function v(D){return n("f","<-",ba)("y","<-",Q)(U,"<|>",ga,"<|>",$,"<|>",t,function(da){return da.f(D,da.y)})}var B=xa(d,[[],[],[],[],[]],j),S=B[1],M=B[2],I=B[3];j=B[4];var N=ia(B[0]),aa=ia(S),ba=ia(M);B=sa(ia(I),"");j=sa(ia(j),"");var U=e("right",N),ga=e("left",aa),$=e("non",ba);j=w(j,m(la));B=w(B,m(la));var Q=n("pre","<-",B)("x","<-",g)("post","<-",j)(t,function(D){return D.post(D.pre(D.x))});return n("x",
"<-",Q)(c,i,"x","<|>",c,p,"x","<|>",c,v,"x","<|>",t,"x","<?>","operator").resolve()}return Ya(h,b,a)}var y,Fc={}.toString,Gc=[].slice,la=function(a){return a},T=Ea(function(a,b){return a(b)}),vc=parseInt,La=la,wc=la,L=String.fromCharCode,Y=Math.round,na=window.JSParsec={};C(na,{curry:Ea,const_:Jb,isArray:wa,isDefined:Xa,slice:E,foldl:Ya,foldr:xa,map:G,filter:Kb,indexOf:Za,lastIndexOf:Lb,zip:$a,sort:ab,nub:Oa,maybe:Mb,compare:Nb,compose:Ob,compose1:Pb,call:T,id:la,flip:bb,cons:H,consJoin:cb,replicate:db,
negate:Qb,null_:eb,elem:Pa,isSpace:fb,isUpper:Rb,isLower:Sb,isAlpha:gb,isAlphaNum:Tb,isDigit:Ub,isHexDigit:Vb,isOctDigit:Wb,digitToInt:hb,range:Hc,extend:C,namespace:Oc,toInteger:vc,fromInteger:La,fromIntegral:wc,fst:Ic,snd:Jc,uncurry:Kc,lookup:Lc,readHex:Mc,readOct:Nc,chr:L,round:Y});var ya=new Xb;Qa.prototype.toString=Yb();Qa.prototype.dataConstructorToString=Yb(true);fa(R,[["Just","a"],"Nothing"]);fa(Fa,["LT","EQ","GT"]);fa(za,[["Left","a"],["Right","b"]]);var Aa={$:{func:T,fixity:oa(0)},".":{func:Pb,
fixity:oa(9)},":":{func:H,fixity:oa(5)}};Array.prototype.resolve=function(){return ha(this)};L=new jb;C(na,{data:fa,ADT:Qa,record:ya,Maybe:R,Ordering:Fa,Either:za,operators:Aa,infix:Zb,infixl:ca,infixr:oa,arr:Sc,op:Uc,str:Tc,ex:u,resolve:ha,recurse:L,Recurse:jb,cs:n});Ga.prototype={memoize:false,scrollTo:function(a){this.index=a;this.length=this.input.length-a;return this},scroll:function(a){this.index+=a;this.length-=a;return this},at:function(a){return this.input.charAt(this.index+a)},substring:function(a,
b){return this.input.substring(a+this.index,(b||this.length)+this.index)},substr:function(a,b){return this.input.substring(a+this.index,b||this.length)},toString:function(){var a=this.substring(0);return"PS at "+this.index+" "+(a.length?'"'+a+'"':"Empty")},getCached:function(a){if(this.memoize)if(a=this.cache[a])if(a=a[this.index]){this.index=a.index;this.length=a.length;return a}},putCached:function(a,b,c){if(!this.memoize)return false;c.index=this.index;c.length=this.length;var d=this.cache[a];
d||(d=this.cache[a]={});d[b]=c},sourceLine:function(a){return(a=this.input.substring(0,a).match(/(\r\n)|\r|\n/g))?a.length:0}};var Xc=J(y),Bc=ac,rb=bc;L=rb;var kc=0,Hb=function(a,b){function c(d,e,h){return{func:a,args:[d,e,function(g){return g.success?b(d,e,h):h(g)}]}}c.constructor=q;return c},k=function(){function a(c,d,e){var h={},g=1,j=b.length,i=b[0];for(h.scope=d;g<j;++g)i=Hb(i,b[g]);return i(c,h,e)}var b=G(kb,arguments);a.constructor=q;return a},O=Ob(t,nb),qc=cc,rc=dc,m=ec,Cc=m;Y=ob;var va=
Hb,Z=w,qa=jc(false),Ia=jc(true),P=Sa(function(a,b,c,d){b=C({},b);if(b.success)return b;c.scrollTo(d);b.ast=y;return b}),ja=function(a){return Sa(function(b,c){c=C({},c);c.ast=y;return c})(qa(a),null)},s=qb(function(a,b){if(b.length>0&&b.at(0)==a){b.scroll(1);return J(a)}return Ha(a)}),F=qb(function(a,b){var c=b.at(0);if(b.length>0&&a(c)){b.scroll(1);return J(c)}return Ha(c)}),V=function(a){return Sa(function(b,c,d,e){c=C({},c);c.ast=c.ast.join("");if(c.success)delete c.expecting;else c.expecting=
{at:e,expecting:a};if(!c.ast.length)c.ast=y;return c})(ic(G(s,a)),null)},sa=Sa(function(a,b,c,d){if(!b.success){b=C({},b);b.expecting={at:d,expecting:a}}return b}),Ib=qb(function(a,b){var c;if(typeof a=="string")if(b.substring(0,a.length)==a){b.scroll(a.length);c=J(a)}else c=Ha(a);else if(a.exec){var d=new RegExp("^"+a.source);c=b.substring(0);d=(d=(d=d.exec(c))&&d[0])&&d.length;c=c.substr(0,d);if(d){b.scroll(d);c=J(c)}else c=Ha(a.source)}return c});C(Aa,{"<-":{func:r,fixity:oa(-1)},">>=":{func:Ba,
fixity:ca(1)},"=<<":{func:bb(Ba),fixity:oa(1)},">>":{func:va,fixity:ca(1)},"*>":{func:va,fixity:ca(4)},"<*":{func:hc,fixity:ca(4)},"<$>":{func:Y,fixity:ca(4)},"<*>":{func:fc,fixity:ca(4)},"<**>":{func:Ea(pb)(bb(T)),fixity:ca(4)},"<$":{func:function(a,b){return hc(Cc(value),b)},fixity:ca(4)},"<|>":{func:w,fixity:oa(1)},"<?>":{func:sa,fixity:Zb(0)}});C(na,{sequence:lc,run:Wc,Parser:q,ParseState:Ga,ps:$b,toParser:kb,unexpected:Ra,parsecMap:Y,fmap:Y,liftM:ob,liftM2:pb,liftM3:gc,liftA:Y,liftA2:pb,liftA3:gc,
ap:fc,parserBind:Ba,parserReturn:ec,return_:m,pure:Cc,parserFail:ac,fail:Bc,parserZero:bc,mzero:rb,empty:L,parserPlus:w,parserPlusN:Yc,mplus:Z,do_:k,do2:Hb,bind:r,ret:t,withBound:nb,returnCall:O,lazy:Zc,getPosition:cc,setPosition:dc,getParserState:qc,setParserState:rc,tokens:ic,many:qa,many1:Ia,string:V,char_:s,satisfy:F,label:sa,try_:P,skipMany:ja,match:Ib});var W=function(a){return sa(F(function(b){return Pa(b,a)}),"oneOf("+a+")")},Ab=function(a){return sa(F(function(b){return!Pa(b,a)}),"noneOf("+
a+")")},Bb=[F,fb,"<?>","space"].resolve();Y=[ja,Bb,"<?>","white space"].resolve();va=[s,"\n","<?>","new-line"].resolve();Z=[s,"\t","<?>","tab"].resolve();var yc=[F,Rb,"<?>","uppercase letter"].resolve();Ib=[F,Sb,"<?>","lowercase letter"].resolve();T=[F,Tb,"<?>","letter or digit"].resolve();L=[F,gb,"<?>","letter"].resolve();var Eb=[F,Ub,"<?>","digit"].resolve(),Db=[F,Vb,"<?>","hexadecimal digit"].resolve(),Cb=[F,Wb,"<?>","octal digit"].resolve(),nd=[F,Jb(true)].resolve();C(na,{oneOf:W,noneOf:Ab,space:Bb,
spaces:Y,newline:va,tab:Z,upper:yc,lower:Ib,alphaNum:T,letter:L,digit:Eb,hexDigit:Db,octDigit:Cb,anyChar:nd});C(na,{choice:ia,count:dd,between:pa,option:Ta,optionMaybe:$c,optional:ad,skipMany1:Ua,sepBy:sb,sepBy1:Va,endBy:cd,endBy1:bd,sepEndBy:nc,sepEndBy1:mc,chainl:fd,chainl1:pc,chainr:ed,chainr1:oc,eof:hd,notFollowedBy:tb,manyTill:id,lookAhead:jd,anyToken:gd});fa(Ja,[["LanguageDef",{commentStart:String,commentEnd:String,commentLine:String,nestedComments:Boolean,identStart:q,identLetter:q,opStart:q,
opLetter:q,reservedNames:Array,reservedOpNames:Array,caseSensitive:Boolean}]]);fa(ub,[["TokenParser",{identifier:q,reserved:Function,operator:q,reservedOp:Function,charLiteral:q,stringLiteral:q,natural:q,integer:q,float_:q,naturalOrFloat:q,decimal:q,hexadecimal:q,octal:q,symbol:Function,lexeme:Function,whiteSpace:q,parens:Function,braces:Function,angles:Function,brackets:Function,squares:Function,semi:q,comma:q,colon:q,dot:q,semiSep:Function,semiSep1:Function,commaSep:Function,commaSep1:Function}]]);
C(na,{GenLanguageDef:Ja,GenTokenParser:ub,makeTokenParser:vb});Z=W(":!#$%&*+./<=>?@\\^|-~");Y=Ja.LanguageDef(ya,{commentStart:"",commentEnd:"",commentLine:"",nestedComments:true,identStart:[L,"<|>",s("_")].resolve(),identLetter:[T,"<|>",W("_'")].resolve(),opStart:Z,opLetter:Z,reservedOpNames:[],reservedNames:[],caseSensitive:true});va=Ja.LanguageDef(ya,{commentStart:"{-",commentEnd:"-}",commentLine:"--",nestedComments:true,identStart:L,identLetter:[T,"<|>",W,"_'"].resolve(),opStart:Z,opLetter:Z,reservedOpNames:[],
reservedNames:[],caseSensitive:true});T=Ja.LanguageDef(ya,{commentStart:"/*",commentEnd:"*/",commentLine:"//",nestedComments:true,identStart:L,identLetter:[T,"<|>",W,"_'"].resolve(),opStart:Z,opLetter:Z,reservedOpNames:[],reservedNames:[],caseSensitive:false});L=va.update({reservedOpNames:["::","..","=","\\","|","<-","->","@","~","=>"],reservedNames:["let","in","case","of","if","then","else","data","type","class","default","deriving","do","import","infix","infixl","infixr","instance","module","newtype",
"where","primitive"]});var Dc=L.update({identLetter:[L.identLetter,"<|>",s("#")].resolve(),reservedNames:L.reservedNames.concat(["foreign","import","export","primitive","_ccall_","_casm_","forall"])}),Ec=T.update({reservedNames:["case","class","default","extends","import","in","let","new","of","package"],caseSensitive:true});C(na,{emptyDef:Y,haskellStyle:va,javaStyle:T,haskellDef:Dc,mondrianDef:Ec,getHaskell:function(){return vb(Dc)},getMondrian:function(){return vb(Ec)}});fa(Gb,["AssocNone","AssocLeft",
"AssocRight"]);fa(Ac,[["Infix",q,Gb],["Prefix",q],["Postfix",q]]);C(na,{Assoc:Gb,Operator:Ac,buildExpressionParser:md})})();
