/*

 JSParsec - A parser combinator library for JavaScript

 Version: 1.0.1

 http://code.google.com/p/jsparsec/

 Copyright (c) 2010 Balazs Endresz (balazs.endresz@gmail.com)
 Dual licensed under the MIT and GPL licenses.


 The initial implementation of some combinators and the memoization is derived from:
 http://www.bluishcoder.co.nz/2007/10/javascript-parser-combinators.html

 Most functions should behave like their counterparts in Parsec:
 http://www.haskell.org/haskellwiki/Parsec

*/
(function(){function ta(a){function b(){var c=G(arguments);return c.length>=(a._length===undefined?a.length:a._length)?a.apply(null,c):function(){return b.apply(null,c.concat(G(arguments)))}}return b}function Kb(a){return function(){return a}}function ua(a){return Cc.call(a)=="[object Array]"}function Va(a){return a!==B}function G(a,b){return Dc.call(a,b||0)}function Wa(a,b,c){for(var d=0,e=c.length;d<e;++d)b=a(b,c[d]);return b}function va(a,b,c){for(var d=c.length-1;d>-1;--d)b=a(c[d],b);return b}
function E(a,b){for(var c=[],d=0,e=b.length;d<e;++d)c[d]=a(b[d],d);return c}function Lb(a,b){for(var c=[],d=0,e=a.length;d<e;++d)b(a[d])&&c.push(a[d]);return c}function Xa(a,b){var c=a.length;if(!c)return-1;for(var d=0;d<c;d++)if(a[d]===b)return d;return-1}function Mb(a,b){var c=a.length;if(!c)return-1;for(c=c-1;c>-1;--c)if(a[c]===b)return c;return-1}function Ya(a,b){for(var c=[],d=0,e=Math.min(a.length,b.length);d<e;++d)c[d]=[a[d],b[d]];return c}function Za(a){var b=typeof a;if(b=="object")return a.sort();
if(b=="string")return G(a).sort().join("")}function Ma(a,b){b=b===B?[]:b;var c=a[0],d=G(a,1);return!a.length?[]:Na(c,b)?Ma(d,b):H(c,Ma(d,H(c,b)))}function Nb(a,b,c){if(c.Nothing)return a;if(c.Just)return b(c[0])}function Ob(a,b){return a===b?Da.EQ:a<=b?Da.LT:Da.GT}function C(a,b){for(var c in b)a[c]=b[c];return a}function Pb(a,b){return function(){return a(b.apply(null,arguments))}}function Qb(a,b){return function(c){var d=G(arguments,1);d.unshift(b(c));return a.apply(null,d)}}function $a(a){return function(b,
c){return a(c,b)}}function H(a,b){if(typeof a=="string"&&typeof b=="string")return a+b;return[a].concat(b)}function ab(a,b){if(typeof a=="string"&&typeof b=="string")return a+b;return a+b.join("")}function bb(a,b){for(var c=[],d=0;d<a;++d)c[d]=b;return c}function Rb(a){return-a}function cb(a){return!a.length}function Na(a,b){return(b.indexOf?b.indexOf(a):Xa(b,a))!=-1}function db(a){return/^\s$/.test(a)}function Sb(a){return a.toUpperCase()==a}function Tb(a){return a.toLowerCase()==a}function Ub(a){return/^\w$/.test(a)}
function eb(a){return/^\w$/.test(a)&&/^\D$/.test(a)}function Vb(a){return/^\d$/.test(a)}function fb(a){return/^[0-9A-Fa-f]$/.test(a)}function Wb(a){return/^[0-7]$/.test(a)}function gb(a){if(!fb(a))throw"Data.Char.digitToInt: not a digit "+a;return parseInt(a,16)}function Ec(a,b){return{indexOf:function(c){return c>=a&&c<=b?true:-1},toString:function(){return"range("+a+", "+b+")"}}}function Fc(a){return a[0]}function Gc(a){return a[1]}function Hc(a){return function(b){return a(b[0],b[1])}}function Ic(a,
b){var c=b.length;if(!c)return Q.Nothing;for(var d=0;d<c;++d)if(b[d][0]===a)return Q.Just(b[d][1]);return Q.Nothing}function Jc(){var a,b;E(function(c){b=c.split(".");a=window[b[0]]=window[b[0]]||{};E(function(d){a=a[d]=a[d]||{}},b.slice(1))},arguments);return a}function Xb(){}function Kc(a,b){if(!/^[0-9]$/.test(b))return b;if(typeof a!="object")return b;var c=0;for(var d in a){if(a.hasOwnProperty(d)&&c==b)return d;c++}return-1}function Oa(){}function Yb(a){return function(){var b=[],c=this._recordset;
if(c&&!ua(c)){for(var d in c){var e=a?c[d].name||c[d]:this[d];if(!a&&e instanceof Function)e=e.constructor!=Function?e.constructor.name:"Function("+e.name+")";b.push(d+" :: "+e)}c=bb(this._dataConstructor.length+2," ").join("");b="{"+b.join("\n"+c+",")+"\n"+c+"}"}else{for(d=0;d in this;d++)b.push(a?c[d].name||c[d]:this[d]);b=b.join(" ")}return"("+this._dataConstructor+(b?" ":"")+b+")"}}function da(a,b){function c(j,i){function o(y,u){var z=y instanceof Xb,R=z?u:G(arguments),K=new a,I=0;K.constructor=
a;K._recordset=p&&i[0]||i;K._dataConstructor=j;K.update=function(ea){var Y={};for(var O in i[0]){Y[O]=this[O];if(O in ea)Y[O]=ea[O]}return o(wa,Y)};K[j]=true;if(R!==B)for(var L in R)if(R.hasOwnProperty(L)&&L!=j){if(z&&i&&p)if(!(L in i[0]))throw"The accessor '"+L+"' is not defined for the data constructor '"+j+"'";var Z=Kc(i[0],L),$=R[I]!==undefined?R[I]:R[Z],T=p?i[0][Z]:i[I];if(T.name&&!(T==$.constructor||$ instanceof T))throw"Type error: expecting '"+T.name+"' instead of '"+$.constructor.name+"' in the argument '"+
(Z||I)+"' of the data constructor '"+j+"' of type '"+a.name+"'";K[Z]=K[I]=K[L]=R[L];I++}else if(L==j)throw"Accessor has the same name as the data constructor: '"+j+"'";return K}var p=i&&typeof i[0]=="object";return o}if(a.constructors)throw"Type constructor has been already defined: '"+a.name+"'";a.constructors=b;a.prototype=new Oa;for(var d=0,e=b.length;d<e;++d){var g=typeof b[d]!="object",h=g?b[d]:b[d][0];if(h in{})throw"The name of the data constructor can't be a property of Object.prototype as well!";
a[h]=g?c(h)():c(h,G(b[d],1));if(!g)a[h]._length=G(b[d],1).length}}function Q(){}function Da(){}function xa(){}function aa(a){return["l",a]}function ma(a){return["r",a]}function Zb(a){return["x",a]}function Lc(a){if(a)if(!a._String){var b=ya[a];if(a._Op&&!b)return"l";return b&&(b.fixity[0]||"l")}}function Mc(a){if(a)if(!a._String){var b=ya[a];if(a._Op&&!b)return 9;return b&&(Va(b.fixity[1])?b.fixity[1]:9)}}function hb(a,b,c){var d;if(a[b]._Op){delete a[b]._Op;d=a[b]}else d=ya[a[b]].func;d=d(a[b-1],
a[b+1]);a.splice(b-1,3,d);return fa(a,c)}function Nc(a){a._Array=true;return a}function Oc(a){a=new String(a);a._String=true;return a}function Pc(a){a._Op=true;return a}function fa(a,b){a=E(function(i){if(i&&i._Array){delete i._Array;return i}return ua(i)?fa(i,b):i&&i.CallStream?i.resolve(b):i},a);if(b)a=E(function(i){return i instanceof ib?b:i},a);for(var c=[],d=[],e=0,g=a.length;e<g;++e){var h=a[e],j=false;if(ya[h])j=true;if(h&&h._String){j=false;h=h.toString()}if(h&&h._Op)j=true;if(!j&&e!=g-1)c.push(h);
else{e==g-1&&c.push(h);c=c.length>1?c[0].apply(null,c.slice(1)):c[0];d.push(c);e!=g-1&&d.push(h);c=[]}}a=d;d=E(Lc,a);g=E(Mc,a);h=Lb(g,Va).sort().pop();e=Xa(g,h);g=Mb(g,h);return d[e]=="l"?hb(a,e,b):d[g]=="r"?hb(a,g,b):d[e]=="x"?hb(a,e,b):a[0]}function Qc(){function a(){return d.apply(null,arguments)}function b(){return(e?d:b.resolve()).apply(null,arguments)}var c=arguments,d,e;b.resolve=function(g){if(e)return d;d=fa(c,g||a);c=null;e=true;return d};b.CallStream=true;b.constructor=r;return b}function ib(){}
function m(){function a(g,h,j){return d(g,h,j)}function b(g,h,j){if(e||g instanceof Ea)return(e?d:b.resolve())(g,h,j);c.push(fa(arguments,a));return b}var c=[],d,e;c.push(fa(arguments,a));b.resolve=function(){if(e)return d;d=k.apply(null,c);e=true;c=null;return d};b.CallStream=true;b.constructor=r;return b}function Ea(a,b){this.input=a;this.index=b||0;this.length=a.length-this.index;this.cache={};return this}function $b(a){return new Ea(a)}function F(a,b,c){return{ast:a,success:b===B?true:b,expecting:c}}
function za(a){return F(B,false,a)}function Pa(a){return function(b,c,d){return d(F(null,false,{unexpected:c[a]}))}}function ac(a){return function(b,c,d){return d(F(B,false,a))}}function bc(a,b,c){return c(F(B,false))}function jb(a){return typeof a=="string"?U(a):ua(a)?fa(a):a}function Rc(a){for(;a&&a.func;)a=a.func.apply(null,a.args||[])}function kb(a,b){b=b||0;b++;if(a&&a.func){a=a.func.apply(null,a.args||[]);b%500==0?setTimeout(function(){kb(a,b)},1):kb(a,b)}else b=0}function Sc(a,b,c,d,e){var g=
b instanceof Ea?b:$b(b);(e?kb:Rc)({func:a,args:[g,{},function(h){h.state=g;delete h.index;delete h.length;if(h.success){delete h.error;delete h.expecting}else{h.error=lb(h.expecting,h.state);d&&d(h.error)}c(h)}]})}function lb(a,b,c,d){c=c===undefined?b.index:c;if(typeof a=="string"){var e=b.input.split("\n"),g=e.length,h=b.input.substr(c).split("\n").length;g=g-h+1;e=c-e.splice(0,g-1).join("\n").length;b=d||b.input.substr(c,a.length).substr(0,6);return'Unexpected "'+(b.length?b:"end of file")+(d?
"":'", expecting "'+a)+'" at line '+g+" char "+e}if(ua(a)){a=E(function(j){return typeof j=="object"?j.expecting:j},a);return lb(a.join('" or "'),b)}else if(typeof a=="object")return lb(a.expecting,b,a.at,a.unexpected)}function r(){}function mb(a,b){return function(c,d,e){return{func:a,args:[c,d,function(g){return g.success?{func:b(g.ast),args:[c,d,e]}:e(g)}]}}}function q(a,b){if(a=="scope")throw"Can't use 'scope' as an identifier!";return function(c,d,e){return{func:b,args:[c,d,function(g){if(g.success)d[a]=
g.ast;g=C({},g);delete g.ast;return e(g)}]}}}function t(a,b){b&&G(arguments);return function(c,d,e){return{func:function(){var g;if(typeof a=="string"){if(!(a in d))throw'Not in scope: "'+a+'"';g=d[a]}else g=a(d);return e(F(g))}}}}function nb(a){var b=G(arguments,1);return function(c){return a.apply(null,E(function(d){return c[d]},b))}}function cc(a,b,c){return c(F(a.index))}function dc(a){return function(b,c,d){b.scrollTo(c[a]);return d(Tc)}}function ec(a){return function(b,c,d){return d(F(a))}}
function fc(a,b){return k(q("a",a),q("b",b),t(function(c){return c.a(c.b)}))}function ob(a,b){return k(q("x1",b),M(a,"x1"))}function pb(a,b,c){return k(q("x1",b),q("x2",c),M(a,"x1","x2"))}function gc(a,b,c,d){return k(q("x1",b),q("x2",c),q("x3",d),M(a,"x1","x2","x3"))}function hc(a,b){return k(q("a",a),b,t("a"))}function w(a,b){function c(d,e,g){return{func:a,args:[d,e,function(h){function j(o){var p=o.expecting;if(p)if(ua(p))i=i.concat(p);else i.push(p);if(o.success)delete o.expecting;else o.expecting=
i}var i=[];j(h);return h.ast!==undefined?{func:g,args:[h]}:{func:b,args:[d,e,function(o){j(o);return g(o)}]}}]}}c.constructor=r;return c}function Uc(){var a=E(jb,arguments);return function(b,c,d){for(var e=1,g=a.length,h=a[0];e<g;++e)h=w(h,a[e]);return h(b,c,d)}}function ic(a){return function(b,c,d){function e(i){return function(o,p,y){return{func:i,args:[o,p,function(u){g++;if(!u.success)return y(u);u.ast!==B&&h.push(u.ast);return g<j?e(a[g])(o,p,y):y(u)}]}}}var g=0,h=[],j=a.length;return{func:e(a[g]),
args:[b,c,function(i){i=C({},i);i.ast=h;i.success&&delete i.expecting;return d(i)}]}}}function jc(a){return function(b){return function(c,d,e){function g(i){return function(o,p,y){return{func:i,args:[o,p,function(u){if(!u.success)return y(u);h=true;u.ast!==B&&j.push(u.ast);return g(i)(o,p,y)}]}}}var h=false,j=[];return{func:g(b),args:[c,d,function(i){i=C({},i);i.success=!a||h&&a;i.ast=j;i.success&&delete i.expecting;return e(i)}]}}}}function qb(a){return function(b){var c=kc++,d=function(e,g,h){g=
e.index;var j=e.getCached(c);if(j!==B)return h(j);j=a(b,e,g);e.putCached(c,g,j);return h(j)};d.constructor=r;return d}}function Qa(a){return function(b,c){var d=kc++,e=function(g,h,j){var i=g.index,o=g.getCached(d);if(o!==B)return j(o);return{func:b,args:[g,h,function(p){p=a(c,p,g,i);g.putCached(d,i,p);return j(p)}]}};e.constructor=r;return e}}function lc(a){function b(c,d){return k(q("x",c),q("xs",d),t(nb(H,"x","xs")))}return va(b,n([]),a)}function Vc(a){return function(b,c,d){return a()(b,c,d)}}
function ga(a){return va(w,rb,a)}function Ra(a,b){return w(b,n(a))}function Wc(a){return Ra(Q.Nothing,ob(Q.Just,a))}function Xc(a){return w(k(a,n(null)),n(null))}function Sa(a){return k(a,ha(a))}function sb(a,b){return w(Ta(a,b),n([]))}function Ta(a,b){return k(q("x",a),q("xs",na(k(b,a))),M(H,"x","xs"))}function mc(a,b){return k(q("x",a),w(k(b,q("xs",function(c,d,e){return nc(a,b)(c,d,e)}),t(function(c){return H(c.scope.x,c.xs)})),t(function(c){return[c.x]})))}function nc(a,b){return w(mc(a,b),n([]))}
function Yc(a,b){return Fa(k(q("x",a),b,t("x")))}function Zc(a,b){return na(k(q("x",a),b,t("x")))}function $c(a,b){return a<=0?n([]):lc(bb(a,b))}function ad(a,b,c){return w(oc(a,b),n(c))}function bd(a,b,c){return w(pc(a,b),n(c))}function pc(a,b){function c(d){var e=k(q("f",b),q("y",a),function(g,h,j){return c(h.f(d,h.y))(g,h,j)});return w(e,n(d))}return k(q("x",a),function(d,e,g){return c(e.x)(d,e,g)})}function oc(a,b){function c(e){var g=k(q("f",b),q("y",d),function(h,j,i){return i(F(j.f(e,j.y)))});
return w(g,n(e))}var d=k(q("x",a),function(e,g,h){return c(g.x)(e,g,h)});return d}function cd(a,b,c){b=a.at(0);if(b.length){a.scroll(1);return c(F(b))}return c(za("anyToken"))}function dd(a,b,c){return c(F(B,!a.length,a.length?"end of input":B))}function tb(a){return N(w(k(q("c",N(a)),Pa("c")),n(null)))}function ed(a,b){function c(e,g,h){return d(e,g,h)}var d=w(k(b,n([])),k(q("x",a),q("xs",c),M(H,"x","xs")));return d}function fd(a){return k(q("state",cc),q("x",a),dc("state"),t("x"))}function Ga(){}
function ub(){}function vb(a){function b(f){return c(U(f))}function c(f){return k(q("x",f),qc,t("x"))}function d(f,l,v){return rc(f,l,v)}function e(f,l,v){return sc(f,l,v)}function g(f,l,v){return wb(f,l,v)}function h(f){return oa(b("("),b(")"),f)}function j(f){return oa(b("{"),b("}"),f)}function i(f){return oa(b("<"),b(">"),f)}function o(f){return oa(b("["),b("]"),f)}function p(f){return sb(f,xb)}function y(f){return sb(f,yb)}function u(f){return Ta(f,xb)}function z(f){return Ta(f,yb)}function R(f){return k(s(f[0]),
n(f[1]))}function K(f){return N(k(U(f[0]),n(f[1])))}function I(f,l){return m("digits","<-",Fa,l)(t,function(v){return Wa(function(J,Ha){return f*J+tc(gb(Ha))},0,v.digits)}).resolve()}function L(f,l,v){return pa(f,l,v)}function Z(f,l){return(l+uc(gb(f)))/10}function $(f){return f<0?1/$(-f):Ia(Math.pow(10,f))}function T(f){return[m("fract","<-",gd)("expo","<-",Ra,1,vc)(t,function(l){return Ia(f+l.fract)*l.expo}),"<|>",m("expo","<-",vc)(t,function(l){return Ia(f)*l.expo})].resolve()}function ea(f){return m("f",
"<-",T,f)(M,xa.Right,"f").resolve()}function Y(f){return[c,"$",N,"$",m(U(f))(tb,a.opLetter,"<?>","end of "+f)].resolve()}function O(f){return Aa(Za(a.reservedOpNames),f)}function A(f){function l(J){return!J.length?n(null):k(qa(v(J[0]),""+f),l(G(J,1)))}function v(J){return eb(J)?w(s(J.toLowerCase()),s(J.toUpperCase())):s(J)}return a.caseSensitive?U(f):k(l(f),n(f))}function ba(f){return[c,"$",N,"$",m(A(f))(tb,a.identLetter,"<?>","end of "+f)].resolve()}function Aa(f,l){function v(J){if(!J.length)return false;
var Ha=Ob(J[0],l);return Ha.LT?v(G(J,1)):Ha.EQ?true:Ha.GT?false:null}return v(f)}function zb(f){f=a.caseSensitive?f:f.toLowerCase();return Aa(hd,f)}if(!a.LanguageDef)throw"Type error: unexpected '"+a.constructor.name+"', expecting 'GenLanguageDef.LanguageDef'";var Ba=Sa(D(db)),Ua=m(N(U(a.commentLine)))(ha,D(function(f){return f!="\n"}))(n,null).resolve(),x=Ma(G(a.commentEnd+a.commentStart)),rc=[k(N(U(a.commentEnd)),n(null)),"<|>",k(Sa(Ab(x)),d),"<|>",k(V(x),d),"<?>","end of comment"].resolve(),sc=
[k(N(U(a.commentEnd)),n(null)),"<|>",k(g,e),"<|>",k(Sa(Ab(x)),e),"<|>",k(V(x),e),"<?>","end of comment"].resolve();x=a.nestedComments?sc:rc;var wb=k(N(U(a.commentStart)),x);x=cb(a.commentLine);var W=cb(a.commentStart),qc=(x&&W?[ha,[Ba,"<?>",""]]:x?[ha,[Ba,"<|>",wb,"<?>",""]]:W?[ha,[Ba,"<|>",Ua,"<?>",""]]:[ha,[Ba,"<|>",Ua,"<|>",wb,"<?>",""]]).resolve(),yb=b(";"),xb=b(",");Ba=b(".");Ua=b(":");x=Ya("abfnrtv\\\"'","a\u0008\u000c\n\r\t\u000b\\\"'");W=Ya(["NUL","SOH","STX","ETX","EOT","ENQ","ACK","BEL",
"DLE","DC1","DC2","DC3","DC4","NAK","SYN","ETB","CAN","SUB","ESC","DEL"]+["BS","HT","LF","VT","FF","CR","SO","SI","EM","FS","GS","RS","US","SP"],["NUL","SOH","STX","ETX","EOT","ENQ","ACK","BEL","DLE","DC1","DC2","DC3","DC4","NAK","SYN","ETB","CAN","SUB","ESC","DEL"]+["BS","HT","LF","VT","FF","CR","SO","SI","EM","FS","GS","RS","US","SP"]);x=ga(E(R,x));var ca=ga(E(K,W));W=D(function(f){return f!='"'&&f!="\\"&&f>"\u0016"});var ra=s("&"),Ja=m(Fa,Bb)(s("\\"),"<?>","end of string gap").resolve(),Ka=m("code",
"<-",L,"<|>",k(s("o"),I(8,Cb)),"<|>",k(s("x"),I(16,Db)))(t(function(f){return toEnum(Ia(f.code))})).resolve(),ia=m(s("^"))("code","<-",wc)(t(function(f){return toEnum(fromEnum(f.code)-fromEnum("A"))})).resolve();ca=[x,"<|>",Ka,"<|>",ca,"<|>",ia,"<?>","escape code"].resolve();x=k(s("\\"),ca);x=[D(function(f){return f!="'"&&f!="\\"&&f>"\u0016"}),"<|>",x,"<?>","literal character"].resolve();x=[c,[oa,s("'"),[s("'"),"<?>","end of character"],x],"<?>","character"].resolve();ra=m(s("\\"))(m(Ja)(n,Q.Nothing),
"<|>",m(ra)(n,Q.Nothing),"<|>",m("esc","<-",ca)(M,Q.Just,"esc")).resolve();W=[m("c","<-",W)(M,Q.Just,"c"),"<|>",ra,"<?>","string character"].resolve();W=c([m("str","<-",oa,s('"'),[s('"'),"<?>","end of string"],[na,W])(t,function(f){return va(ta(Nb)(ja,ta(H)),"",f.str)}),"<?>","literal string"].resolve());var pa=I(10,Eb);ra=m(V,"xX")(I,16,Db).resolve();Ja=m(V,"oO")(I,8,Cb).resolve();var gd=[m(s("."))("digits","<-",Fa,Eb,"<?>","fraction")(t,function(f){return va(Z,0,f.digits)}),"<?>","fraction"].resolve();
ca=[[s("-"),">>",n,Rb],"<|>",[s("+"),">>",n,ja],"<|>",n,ja].resolve();var vc=[m(V,"eE")("f","<-",ca)("e","<-",pa,"<?>","exponent")(M,$,"f","e"),"<?>","exponent"].resolve();Ka=m("n","<-",pa)(function(f,l,v){return T(l.n)(f,l,v)}).resolve();ia=m("n","<-",pa)(function(f,l,v){return Ra(xa.Left(l.n),ea(l.n))(f,l,v)}).resolve();var Ca=[m("n","<-",ra,"<|>",Ja)(M,xa.Left,"n"),"<|>",ia,"<|>",ea(0),"<|>",n,xa.Left(0)].resolve(),La=[k(s("0"),Ca),"<|>",ia].resolve();Ca=[[m(s,"0")(ra,"<|>",Ja,"<|>",pa,"<|>",n,
0),"<?>",""].resolve(),"<|>",pa].resolve();ia=m("f","<-",c,ca)("n","<-",Ca)(t,function(f){return f.f(f.n)});ca=[c,La,"<?>","number"].resolve();Ka=[c,Ka,"<?>","float"].resolve();ia=[c,ia,"<?>","integer"].resolve();Ca=[c,Ca,"<?>","natural"].resolve();La=[m("c","<-",a.opStart)("cs","<-",na,a.opLetter)(M,ab,"c","cs"),"<?>","operator"].resolve();La=[c,"$",N,"$",m("name","<-",La)(function(f,l,v){return(O(l.name)?Pa("reserved operator "+l.name):n(l.name))(f,l,v)})].resolve();var Fb=[m("c","<-",a.identStart)("cs",
"<-",na,a.identLetter)(M,ab,"c","cs"),"<?>","identifier"].resolve();Fb=[c,"$",N,"$",m("name","<-",Fb)(function(f,l,v){return(zb(l.name)?Pa("reserved word "+l.name):n(l.name))(f,l,v)})].resolve();var xc=Za(a.reservedNames),hd=a.caseSensitive?xc:E(function(f){return f.toLowerCase()},xc);return ub.TokenParser(wa,{identifier:Fb,reserved:ba,operator:La,reservedOp:Y,charLiteral:x,stringLiteral:W,natural:Ca,integer:ia,float_:Ka,naturalOrFloat:ca,decimal:pa,hexadecimal:ra,octal:Ja,symbol:b,lexeme:c,whiteSpace:qc,
parens:h,braces:j,angles:i,brackets:o,squares:o,semi:yb,comma:xb,colon:Ua,dot:Ba,semiSep:y,semiSep1:z,commaSep:p,commaSep1:u})}function Gb(){}function Hb(){}function id(a,b){function c(h,j){return function(i,o,p){return h(o[j])(i,o,p)}}function d(h,j){if(!(h instanceof Hb))throw"Type error: expecting type 'Operator' instead of "+h.constructor;var i=h[0],o=j[0],p=j[1],y=j[2],u=j[3];j=j[4];if(h.Infix){var z=h[1];if(z.AssocNone)return[o,p,H(i,y),u,j];if(z.AssocLeft)return[o,H(i,p),y,u,j];if(z.AssocRight)return[H(i,
o),p,y,u,j]}if(h.Prefix)return[o,p,y,H(i,u),j];if(h.Postfix)return[o,p,y,u,H(i,j)]}function e(h,j){return N(k(j,yc("ambiguous use of a "+h+" associative operator")))}function g(h,j){function i(A){return[m("f","<-",L)("y","<-",m("z","<-",O)(c,o,"z"))(t,function(ba){return ba.f(A,ba.y)}),"<|>",ea,"<|>",Y].resolve()}function o(A){return w(i(A),n(A))}function p(A){return[m("f","<-",Z)("y","<-",O)(function(ba,Aa,zb){return y(Aa.f(A,Aa.y))(ba,Aa,zb)}),"<|>",T,"<|>",Y].resolve()}function y(A){return w(p(A),
n(A))}function u(A){return m("f","<-",$)("y","<-",O)(T,"<|>",ea,"<|>",Y,"<|>",t,function(ba){return ba.f(A,ba.y)}).resolve()}var z=va(d,[[],[],[],[],[]],j),R=z[1],K=z[2],I=z[3];j=z[4];var L=ga(z[0]),Z=ga(R),$=ga(K);z=qa(ga(I),"");j=qa(ga(j),"");var T=e("right",L),ea=e("left",Z),Y=e("non",$);j=w(j,n(ja));z=w(z,n(ja));var O=m("pre","<-",z)("x","<-",h)("post","<-",j)(t,function(A){return A.post(A.pre(A.x))}).resolve();return m("x","<-",O)(c,i,"x","<|>",c,p,"x","<|>",c,u,"x","<|>",t,"x","<?>","operator").resolve()}
return Wa(g,b,a)}var B,Cc={}.toString,Dc=[].slice,ja=function(a){return a},S=ta(function(a,b){return a(b)}),tc=parseInt,Ia=ja,uc=ja,ka=window.JSParsec={};C(ka,{curry:ta,const_:Kb,isArray:ua,isDefined:Va,slice:G,foldl:Wa,foldr:va,map:E,filter:Lb,indexOf:Xa,lastIndexOf:Mb,zip:Ya,sort:Za,nub:Ma,maybe:Nb,compare:Ob,compose:Pb,compose1:Qb,call:S,id:ja,flip:$a,cons:H,consJoin:ab,replicate:bb,negate:Rb,null_:cb,elem:Na,isSpace:db,isUpper:Sb,isLower:Tb,isAlpha:eb,isAlphaNum:Ub,isDigit:Vb,isHexDigit:fb,isOctDigit:Wb,
digitToInt:gb,range:Ec,extend:C,namespace:Jc,toInteger:tc,fromInteger:Ia,fromIntegral:uc,fst:Fc,snd:Gc,uncurry:Hc,lookup:Ic});var wa=new Xb;Oa.prototype.toString=Yb();Oa.prototype.dataConstructorToString=Yb(true);da(Q,[["Just","a"],"Nothing"]);da(Da,["LT","EQ","GT"]);da(xa,[["Left","a"],["Right","b"]]);var ya={$:{func:S,fixity:ma(0)},".":{func:Qb,fixity:ma(9)},":":{func:H,fixity:ma(5)}};Array.prototype.resolve=function(){return fa(this)};var P=new ib;C(ka,{data:da,ADT:Oa,record:wa,Maybe:Q,Ordering:Da,
Either:xa,operators:ya,infix:Zb,infixl:aa,infixr:ma,arr:Nc,op:Pc,str:Oc,ex:Qc,resolve:fa,recurse:P,Recurse:ib,cs:m});Ea.prototype={memoize:false,scrollTo:function(a){this.index=a;this.length=this.input.length-a;return this},scroll:function(a){this.index+=a;this.length-=a;return this},at:function(a){return this.input.charAt(this.index+a)},substring:function(a,b){return this.input.substring(a+this.index,(b||this.length)+this.index)},substr:function(a,b){return this.input.substring(a+this.index,b||this.length)},
toString:function(){var a=this.substring(0);return"PS at "+this.index+" "+(a.length?'"'+a+'"':"Empty")},getCached:function(a){if(this.memoize)if(a=this.cache[a])if(a=a[this.index]){this.index=a.index;this.length=a.length;return a}},putCached:function(a,b,c){if(!this.memoize)return false;c.index=this.index;c.length=this.length;var d=this.cache[a];d||(d=this.cache[a]={});d[b]=c}};var Tc=F(B),yc=ac,rb=bc;P=rb;var kc=0,Ib=function(a,b){function c(d,e,g){return{func:a,args:[d,e,function(h){return h.success?
b(d,e,g):g(h)}]}}c.constructor=r;return c},k=function(){function a(c,d,e){var g={},h=1,j=b.length,i=b[0];for(g.scope=d;h<j;++h)i=Ib(i,b[h]);return i(c,g,e)}var b=E(jb,arguments);a.constructor=r;return a},M=Pb(t,nb),n=ec,zc=n,la=ob,sa=Ib,X=w,na=jc(false),Fa=jc(true),N=Qa(function(a,b,c,d){if(b.success)return b;c.scrollTo(d);return za(b.expecting)}),ha=function(a){return Qa(function(b,c){c=C({},c);c.ast=B;return c})(na(a),null)},s=qb(function(a,b){if(b.length>0&&b.at(0)==a){b.scroll(1);return F(a)}return za(a)}),
D=qb(function(a,b){var c=b.at(0);if(b.length>0&&a(c)){b.scroll(1);return F(c)}return za(c)}),U=function(a){return Qa(function(b,c,d,e){c.ast=c.ast.join("");c=C({},c);if(c.success)delete c.expecting;else c.expecting={at:e,expecting:a};if(!c.ast.length)c.ast=B;return c})(ic(E(s,a)),null)},qa=Qa(function(a,b,c,d){if(!b.success){b=C({},b);b.expecting={at:d,expecting:a}}return b}),Jb=qb(function(a,b){var c;if(typeof a=="string")if(b.substring(0,a.length)==a){b.scroll(a.length);c=F(a)}else c=za(a);else if(a.exec){var d=
new RegExp("^"+a.source);c=b.substring(0);d=(d=(d=d.exec(c))&&d[0])&&d.length;c=c.substr(0,d);if(d){b.scroll(d);c=F(c)}else c=za(a.source)}return c});C(ya,{"<-":{func:q,fixity:ma(-1)},">>=":{func:mb,fixity:aa(1)},"=<<":{func:$a(mb),fixity:ma(1)},">>":{func:sa,fixity:aa(1)},"*>":{func:sa,fixity:aa(4)},"<*":{func:hc,fixity:aa(4)},"<$>":{func:la,fixity:aa(4)},"<*>":{func:fc,fixity:aa(4)},"<**>":{func:ta(pb)($a(S)),fixity:aa(4)},"<$":{func:function(a,b){return hc(zc(value),b)},fixity:aa(4)},"<|>":{func:w,
fixity:ma(1)},"<?>":{func:qa,fixity:Zb(0)}});C(ka,{sequence:lc,run:Sc,Parser:r,ParseState:Ea,ps:$b,toParser:jb,unexpected:Pa,parsecMap:la,fmap:la,liftM:ob,liftM2:pb,liftM3:gc,liftA:la,liftA2:pb,liftA3:gc,ap:fc,parserBind:mb,parserReturn:ec,return_:n,pure:zc,parserFail:ac,fail:yc,parserZero:bc,mzero:rb,empty:P,parserPlus:w,parserPlusN:Uc,mplus:X,do_:k,do2:Ib,bind:q,ret:t,withBound:nb,returnCall:M,lazy:Vc,getParserState:cc,setParserState:dc,tokens:ic,many:na,many1:Fa,string:U,char_:s,satisfy:D,label:qa,
try_:N,skipMany:ha,match:Jb});var V=function(a){return qa(D(function(b){return Na(b,a)}),"oneOf("+a+")")},Ab=function(a){return qa(D(function(b){return!Na(b,a)}),"noneOf("+a+")")},Bb=[D,db,"<?>","space"].resolve();la=[ha,Bb,"<?>","white space"].resolve();sa=[s,"\n","<?>","new-line"].resolve();X=[s,"\t","<?>","tab"].resolve();var wc=[D,Sb,"<?>","uppercase letter"].resolve();Jb=[D,Tb,"<?>","lowercase letter"].resolve();S=[D,Ub,"<?>","letter or digit"].resolve();P=[D,eb,"<?>","letter"].resolve();var Eb=
[D,Vb,"<?>","digit"].resolve(),Db=[D,fb,"<?>","hexadecimal digit"].resolve(),Cb=[D,Wb,"<?>","octal digit"].resolve(),jd=[D,Kb(true)].resolve();C(ka,{oneOf:V,noneOf:Ab,space:Bb,spaces:la,newline:sa,tab:X,upper:wc,lower:Jb,alphaNum:S,letter:P,digit:Eb,hexDigit:Db,octDigit:Cb,anyChar:jd});var oa=ta(function(a,b,c){return k(a,q("x",c),b,t("x"))});C(ka,{choice:ga,count:$c,between:oa,option:Ra,optionMaybe:Wc,optional:Xc,skipMany1:Sa,sepBy:sb,sepBy1:Ta,endBy:Zc,endBy1:Yc,sepEndBy:nc,sepEndBy1:mc,chainl:bd,
chainl1:pc,chainr:ad,chainr1:oc,eof:dd,notFollowedBy:tb,manyTill:ed,lookAhead:fd,anyToken:cd});da(Ga,[["LanguageDef",{commentStart:String,commentEnd:String,commentLine:String,nestedComments:Boolean,identStart:r,identLetter:r,opStart:r,opLetter:r,reservedNames:Array,reservedOpNames:Array,caseSensitive:Boolean}]]);da(ub,[["TokenParser",{identifier:r,reserved:Function,operator:r,reservedOp:Function,charLiteral:r,stringLiteral:r,natural:r,integer:r,float_:r,naturalOrFloat:r,decimal:r,hexadecimal:r,octal:r,
symbol:Function,lexeme:Function,whiteSpace:r,parens:Function,braces:Function,angles:Function,brackets:Function,squares:Function,semi:r,comma:r,colon:r,dot:r,semiSep:Function,semiSep1:Function,commaSep:Function,commaSep1:Function}]]);C(ka,{GenLanguageDef:Ga,GenTokenParser:ub,makeTokenParser:vb});X=V(":!#$%&*+./<=>?@\\^|-~");la=Ga.LanguageDef(wa,{commentStart:"",commentEnd:"",commentLine:"",nestedComments:true,identStart:[P,"<|>",s("_")].resolve(),identLetter:[S,"<|>",V("_'")].resolve(),opStart:X,opLetter:X,
reservedOpNames:[],reservedNames:[],caseSensitive:true});sa=Ga.LanguageDef(wa,{commentStart:"{-",commentEnd:"-}",commentLine:"--",nestedComments:true,identStart:P,identLetter:[S,"<|>",V,"_'"].resolve(),opStart:X,opLetter:X,reservedOpNames:[],reservedNames:[],caseSensitive:true});S=Ga.LanguageDef(wa,{commentStart:"/*",commentEnd:"*/",commentLine:"//",nestedComments:true,identStart:P,identLetter:[S,"<|>",V,"_'"].resolve(),opStart:X,opLetter:X,reservedOpNames:[],reservedNames:[],caseSensitive:false});
P=sa.update({reservedOpNames:["::","..","=","\\","|","<-","->","@","~","=>"],reservedNames:["let","in","case","of","if","then","else","data","type","class","default","deriving","do","import","infix","infixl","infixr","instance","module","newtype","where","primitive"]});var Ac=P.update({identLetter:[P.identLetter,"<|>",s("#")].resolve(),reservedNames:P.reservedNames.concat(["foreign","import","export","primitive","_ccall_","_casm_","forall"])}),Bc=S.update({reservedNames:["case","class","default",
"extends","import","in","let","new","of","package"],caseSensitive:true});C(ka,{emptyDef:la,haskellStyle:sa,javaStyle:S,haskellDef:Ac,mondrianDef:Bc,getHaskell:function(){return vb(Ac)},getMondrian:function(){return vb(Bc)}});da(Gb,["AssocNone","AssocLeft","AssocRight"]);da(Hb,[["Infix",r,Gb],["Prefix",r],["Postfix",r]]);C(ka,{Assoc:Gb,Operator:Hb,buildExpressionParser:id})})();
