/*

 JSParsec - A parser combinator library for JavaScript

 Version: 1.0.1

 http://code.google.com/p/jsparsec/

 Copyright (c) 2010 Balazs Endresz (balazs.endresz@gmail.com)
 Dual licensed under the MIT and GPL licenses.


 The initial implementation of some combinators and the memoization is derived from:
 http://www.bluishcoder.co.nz/2007/10/javascript-parser-combinators.html

 Most functions should behave like their counterparts in Parsec:
 http://www.haskell.org/haskellwiki/Parsec

*/
(function(){function Z(a){function b(){var c=C(arguments);return c.length>=(a._length===undefined?a.length:a._length)?a.apply(null,c):function(){return b.apply(null,c.concat(C(arguments)))}}return b}function Fb(a){return function(){return a}}function ia(a){return xc.call(a)=="[object Array]"}function Ua(a){return a!==x}function C(a,b){return yc.call(a,b||0)}function Gb(a,b,c){for(var d=0,f=c.length;d<f;++d)b=a(b,c[d]);return b}function va(a,b,c){for(var d=c.length-1;d>-1;--d)b=a(c[d],b);return b}
function z(a,b){for(var c=[],d=0,f=b.length;d<f;++d)c[d]=a(b[d],d);return c}function Hb(a,b){for(var c=[],d=0,f=a.length;d<f;++d)b(a[d])&&c.push(a[d]);return c}function Va(a,b){var c=a.length;if(!c)return-1;for(var d=0;d<c;d++)if(a[d]===b)return d;return-1}function Ib(a,b){var c=a.length;if(!c)return-1;for(c=c-1;c>-1;--c)if(a[c]===b)return c;return-1}function Wa(a,b){for(var c=[],d=0,f=Math.min(a.length,b.length);d<f;++d)c[d]=[a[d],b[d]];return c}function Xa(a){var b=typeof a;if(b=="object")return a.sort();
if(b=="string")return C(a).sort().join("")}function Ja(a,b){b=b===x?[]:b;var c=a[0],d=C(a,1);return!a.length?[]:Ka(c,b)?Ja(d,b):R(c,Ja(d,R(c,b)))}function Jb(a,b,c){if(c.Nothing)return a;if(c.Just)return b(c[0])}function Kb(a,b){return a===b?wa.EQ:a<=b?wa.LT:wa.GT}function A(a,b){for(var c in b)a[c]=b[c];return a}function Lb(a,b){return function(){return a(b.apply(null,arguments))}}function Mb(a,b){return function(c){var d=C(arguments,1);d.unshift(b(c));return a.apply(null,d)}}function Ya(a){return function(b,
c){return a(c,b)}}function R(a,b){if(typeof a=="string"&&typeof b=="string")return a+b;return[a].concat(b)}function Za(a,b){if(typeof a=="string"&&typeof b=="string")return a+b;return a+b.join("")}function $a(a,b){for(var c=[],d=0;d<a;++d)c[d]=b;return c}function Nb(a){return-a}function ab(a){return!a.length}function Ka(a,b){return(b.indexOf?b.indexOf(a):Va(b,a))!=-1}function bb(a){return/^\s$/.test(a)}function Ob(a){return a.toUpperCase()==a}function Pb(a){return a.toLowerCase()==a}function Qb(a){return/^\w$/.test(a)}
function cb(a){return/^\w$/.test(a)&&/^\D$/.test(a)}function Rb(a){return/^\d$/.test(a)}function db(a){return/^[0-9A-Fa-f]$/.test(a)}function Sb(a){return/^[0-7]$/.test(a)}function eb(a){if(!db(a))throw"Data.Char.digitToInt: not a digit "+a;return parseInt(a,16)}function zc(a,b){return{indexOf:function(c){return c>=a&&c<=b?true:-1},toString:function(){return"range("+a+", "+b+")"}}}function Ac(a){return a[0]}function Bc(a){return a[1]}function Cc(a){return function(b){return a(b[0],b[1])}}function Dc(){var a,
b;z(function(c){b=c.split(".");a=window[b[0]]=window[b[0]]||{};z(function(d){a=a[d]=a[d]||{}},b.slice(1))},arguments);return a}function Tb(){}function Ec(a,b){if(!/^[0-9]$/.test(b))return b;if(typeof a!="object")return b;var c=0;for(var d in a){if(a.hasOwnProperty(d)&&c==b)return d;c++}return-1}function La(){}function Ub(a){return function(){var b=[],c=this._recordset;if(c&&!ia(c)){for(var d in c){var f=a?c[d].name||c[d]:this[d];if(!a&&f instanceof Function)f=f.constructor!=Function?f.constructor.name:
"Function("+f.name+")";b.push(d+" :: "+f)}c=$a(this._dataConstructor.length+2," ").join("");b="{"+b.join("\n"+c+",")+"\n"+c+"}"}else{for(d=0;d in this;d++)b.push(a?c[d].name||c[d]:this[d]);b=b.join(" ")}return this._dataConstructor+" "+b}}function ja(a,b){function c(j,i){function r(L,D){var Ma=L instanceof Tb,S=Ma?D:C(arguments),I=new a,F=0;I.constructor=a;I._recordset=t&&i[0]||i;I._dataConstructor=j;I.update=function(xa){var ya={};for(var $ in i[0]){ya[$]=this[$];if($ in xa)ya[$]=xa[$]}return r(ka,
ya)};I[j]=true;if(S!==x)for(var M in S)if(S.hasOwnProperty(M)&&M!=j){if(Ma&&i&&t)if(!(M in i[0]))throw"The accessor '"+M+"' is not defined for the data constructor '"+j+"'";var la=Ec(i[0],M),ma=S[F]!==undefined?S[F]:S[la],aa=t?i[0][la]:i[F];if(aa.name&&!(aa==ma.constructor||ma instanceof aa))throw"Type error: expecting '"+aa.name+"' instead of '"+ma.constructor.name+"' in the argument '"+(la||F)+"' of the data constructor '"+j+"' of type '"+a.name+"'";I[la]=I[F]=I[M]=S[M];F++}else if(M==j)throw"Accessor has the same name as the data constructor: '"+
j+"'";return I}var t=i&&typeof i[0]=="object";return r}if(a.constructors)throw"Type constructor has been already defined: '"+a.name+"'";a.constructors=b;a.prototype=new La;for(var d=0,f=b.length;d<f;++d){var g=typeof b[d]!="object",h=g?b[d]:b[d][0];if(h in{})throw"The name of the data constructor can't be a property of Object.prototype as well!";a[h]=g?c(h)():c(h,C(b[d],1));if(!g)a[h]._length=C(b[d],1).length}}function V(){}function wa(){}function na(){}function T(a){return["l",a]}function ba(a){return["r",
a]}function Vb(a){return["x",a]}function Fc(a){if(a)if(!a._String){var b=oa[a];if(a._Op&&!b)return"l";return b&&(b.fixity[0]||"l")}}function Gc(a){if(a)if(!a._String){var b=oa[a];if(a._Op&&!b)return 9;return b&&(Ua(b.fixity[1])?b.fixity[1]:9)}}function fb(a,b,c){var d;if(a[b]._Op){delete a[b]._Op;d=a[b]}else d=oa[a[b]].func;d=d(a[b-1],a[b+1]);a.splice(b-1,3,d);return ca(a,c)}function Hc(a){a._Array=true;return a}function Ic(a){a=new String(a);a._String=true;return a}function Jc(a){a._Op=true;return a}
function ca(a,b){a=z(function(i){if(i&&i._Array){delete i._Array;return i}return ia(i)?ca(i,b):i&&i.CallStream?i.resolve():i},a);if(b)a=z(function(i){return i instanceof gb?b:i},a);for(var c=[],d=[],f=0,g=a.length;f<g;++f){var h=a[f],j=false;if(oa[h])j=true;if(h&&h._String){j=false;h=h.toString()}if(h&&h._Op)j=true;if(!j&&f!=g-1)c.push(h);else{f==g-1&&c.push(h);c=c.length>1?c[0].apply(null,c.slice(1)):c[0];d.push(c);f!=g-1&&d.push(h);c=[]}}a=d;d=z(Fc,a);g=z(Gc,a);h=Hb(g,Ua).sort().pop();f=Va(g,h);
g=Ib(g,h);return d[f]=="l"?fb(a,f,b):d[g]=="r"?fb(a,g,b):d[f]=="x"?fb(a,f,b):a[0]}function gb(){}function n(){function a(g,h,j){return d(g,h,j)}function b(g,h,j){if(g instanceof za)return(f?d:b.resolve())(g,h,j);c.push(ca(arguments,a));return b}var c=[],d,f;c.push(ca(arguments,a));b.resolve=function(){if(f)return d;d=k.apply(null,c);c=null;f=true;return d};b.CallStream=true;return b}function za(a,b){this.input=a;this.index=b||0;this.length=a.length-this.index;this.cache={};return this}function Wb(a){return new za(a)}
function B(a,b,c){return{ast:a,success:b===x?true:b,expecting:c}}function pa(a){return B(x,false,a)}function Na(a){return function(b,c,d){return d(B(null,false,{unexpected:c[a]}))}}function Xb(a){return function(b,c,d){return d(B(x,false,a))}}function Yb(a,b,c){return c(B(x,false))}function hb(a){return typeof a=="string"?N(a):ia(a)?ca(a):a}function Kc(a){for(;a&&a.func;)a=a.func.apply(null,a.args||[])}function ib(a,b){b=b||0;b++;if(a&&a.func){a=a.func.apply(null,a.args||[]);b%500==0?setTimeout(function(){ib(a,
b)},1):ib(a,b)}else b=0}function Lc(a,b,c,d,f){var g=b instanceof za?b:Wb(b);(f?ib:Kc)({func:a,args:[g,{},function(h){h.state=g;delete h.index;delete h.length;if(h.success){delete h.error;delete h.expecting}else{h.error=jb(h.expecting,h.state);d&&d(h.error)}c(h)}]})}function jb(a,b,c,d){c=c===undefined?b.index:c;if(typeof a=="string"){var f=b.input.split("\n"),g=f.length,h=b.input.substr(c).split("\n").length;g=g-h+1;f=c-f.splice(0,g-1).join("\n").length;b=d||b.input.substr(c,a.length).substr(0,6);
return'Unexpected "'+(b.length?b:"end of file")+(d?"":'", expecting "'+a)+'" at line '+g+" char "+f}if(ia(a)){a=z(function(j){return typeof j=="object"?j.expecting:j},a);return jb(a.join('" or "'),b)}else if(typeof a=="object")return jb(a.expecting,b,a.at,a.unexpected)}function o(){}function kb(a,b){return function(c,d,f){return{func:a,args:[c,d,function(g){return g.success?f(b(g.ast)):f(g)}]}}}function q(a,b){if(a=="scope")throw"Can't use 'scope' as an identifier!";return function(c,d,f){return{func:b,
args:[c,d,function(g){if(g.success)d[a]=g.ast;return f(g)}]}}}function u(a,b){b&&C(arguments);return function(c,d,f){return{func:function(){var g;if(typeof a=="string"){if(!(a in d))throw'Not in scope: "'+a+'"';g=d[a]}else g=a(d);return f(B(g))}}}}function lb(a){var b=C(arguments,1);return function(c){return a.apply(null,z(function(d){return c[d]},b))}}function Zb(a,b,c){return c(B(a.index))}function $b(a){return function(b,c,d){b.scrollTo(c[a]);return d(Mc)}}function ac(a){return function(b,c,d){return d(B(a))}}
function Aa(a,b){return qa(function(c){return c[0](c[1])},mb([a,b]))}function bc(a,b){a=Z(a);return function(c,d,f){return{func:b,args:[c,d,function(g){if(!g.success)return f(g);g=A({},g);g.ast=a(g.ast);return f(g)}]}}}function cc(a,b){return k(q("a",a),b,u("a"))}function w(a,b){function c(d,f,g){return{func:a,args:[d,f,function(h){function j(r){var t=r.expecting;if(t)if(ia(t))i=i.concat(t);else i.push(t);if(r.success)delete r.expecting;else r.expecting=i}var i=[];j(h);return h.ast!==undefined?{func:g,
args:[h]}:{func:b,args:[d,f,function(r){j(r);return g(r)}]}}]}}c.constructor=o;return c}function Nc(){var a=z(hb,arguments);return function(b,c,d){for(var f=1,g=a.length,h=a[0];f<g;++f)h=w(h,a[f]);return h(b,c,d)}}function mb(a){return function(b,c,d){function f(i){return function(r,t,L){return{func:i,args:[r,t,function(D){g++;if(!D.success)return L(D);D.ast!==x&&h.push(D.ast);return g<j?f(a[g])(r,t,L):L(D)}]}}}var g=0,h=[],j=a.length;return{func:f(a[g]),args:[b,c,function(i){i=A({},i);i.ast=h;i.success&&
delete i.expecting;return d(i)}]}}}function dc(a){return function(b){return function(c,d,f){function g(i){return function(r,t,L){return{func:i,args:[r,t,function(D){if(!D.success)return L(D);h=true;D.ast!==x&&j.push(D.ast);return g(i)(r,t,L)}]}}}var h=false,j=[];return{func:g(b),args:[c,d,function(i){i=A({},i);i.success=!a||h&&a;i.ast=j;i.success&&delete i.expecting;return f(i)}]}}}}function nb(a){return function(b){var c=ec++,d=function(f,g,h){g=f.index;var j=f.getCached(c);if(j!==x)return h(j);
j=a(b,f,g);f.putCached(c,g,j);return h(j)};d.constructor=o;return d}}function Oa(a){return function(b,c){var d=ec++,f=function(g,h,j){var i=g.index,r=g.getCached(d);if(r!==x)return j(r);return{func:b,args:[g,h,function(t){t=a(c,t,g,i);g.putCached(d,i,t);return j(t)}]}};f.constructor=o;return f}}function fc(a){function b(c,d){return k(q("x",c),q("xs",d),u(lb(R,"x","xs")))}return va(b,m([]),a)}function ob(a){return va(w,pb,a)}function Pa(a,b){return w(b,m(a))}function Oc(a){return Pa(V.Nothing,gc(V.Just,
a))}function Pc(a){return w(k(a,m(null)),m(null))}function Qa(a){return k(a,W(a))}function qb(a,b){return w(Ra(a,b),m([]))}function Ra(a,b){return k(q("x",a),q("xs",da(k(b,a))),O(R,"x","xs"))}function hc(a,b){return k(q("x",a),w(k(b,q("xs",function(c,d,f){return ic(a,b)(c,d,f)}),u(function(c){return R(c.scope.x,c.xs)})),u(function(c){return[c.x]})))}function ic(a,b){return w(hc(a,b),m([]))}function Qc(a,b){return Ba(k(q("x",a),b,u("x")))}function Rc(a,b){return da(k(q("x",a),b,u("x")))}function Sc(a,
b){return a<=0?m([]):fc($a(a,b))}function Tc(a,b,c){return w(jc(a,b),m(c))}function Uc(a,b,c){return w(kc(a,b),m(c))}function kc(a,b){function c(d){var f=k(q("f",b),q("y",a),function(g,h,j){return c(h.f(d,h.y))(g,h,j)});return w(f,m(d))}return k(q("x",a),function(d,f,g){return c(f.x)(d,f,g)})}function jc(a,b){function c(f){var g=k(q("f",b),q("y",d),function(h,j,i){return i(B(j.f(f,j.y)))});return w(g,m(f))}var d=k(q("x",a),function(f,g,h){return c(g.x)(f,g,h)});return d}function Vc(a,b,c){b=a.at(0);
if(b.length){a.scroll(1);return c(B(b))}return c(pa("anyToken"))}function Wc(a,b,c){return c(B(x,!a.length,a.length?"end of input":x))}function rb(a){return G(w(k(q("c",G(a)),Na("c")),m(null)))}function Xc(a,b){function c(f,g,h){return d(f,g,h)}var d=w(k(b,m([])),k(q("x",a),q("xs",c),O(R,"x","xs")));return d}function Yc(a){return k(q("state",Zb),q("x",a),$b("state"),u("x"))}function Ca(){}function sb(){}function tb(a){function b(e){return c(N(e))}function c(e){return k(q("x",e),lc,u("x"))}function d(e,
l,s){return mc(e,l,s)}function f(e,l,s){return nc(e,l,s)}function g(e,l,s){return ub(e,l,s)}function h(e){return ea(b("("),b(")"),e)}function j(e){return ea(b("{"),b("}"),e)}function i(e){return ea(b("<"),b(">"),e)}function r(e){return ea(b("["),b("]"),e)}function t(e){return qb(e,vb)}function L(e){return qb(e,wb)}function D(e){return Ra(e,vb)}function Ma(e){return Ra(e,wb)}function S(e){return k(p(e[0]),m(e[1]))}function I(e){return G(k(N(e[0]),m(e[1])))}function F(e,l){return n("digits","<-",Ba,
l)(u,function(s){return Gb(function(E,Da){return e*E+oc(eb(Da))},0,s.digits)}).resolve()}function M(e,l,s){return fa(e,l,s)}function la(e,l){return(l+pc(eb(e)))/10}function ma(e){return e<0?1/ma(-e):Ea(Math.pow(10,e))}function aa(e){return[n("fract","<-",Zc)("expo","<-",Pa,1,qc)(u,function(l){return Ea(e+l.fract)*l.expo}),"<|>",n("expo","<-",qc)(u,function(l){return Ea(e)*l.expo})].resolve()}function xa(e){return n("f","<-",aa,e)(O,na.Right,"f").resolve()}function ya(e){return[c,"$",G,"$",n(N(e))(rb,
a.opLetter,"<?>","end of "+e)].resolve()}function $(e){return rc(Xa(a.reservedOpNames),e)}function $c(e){function l(E){return!E.length?m(null):k(Fa(s(E[0]),""+e),l(C(E,1)))}function s(E){return cb(E)?w(p(E.toLowerCase()),p(E.toUpperCase())):p(E)}return a.caseSensitive?N(e):k(l(e),m(e))}function ad(e){return[c,"$",G,"$",n($c(e))(rb,a.identLetter,"<?>","end of "+e)].resolve()}function rc(e,l){function s(E){if(!E.length)return false;var Da=Kb(E[0],l);return Da.LT?s(C(E,1)):Da.EQ?true:Da.GT?false:null}
return s(e)}function bd(e){e=a.caseSensitive?e:e.toLowerCase();return rc(cd,e)}if(!a.LanguageDef)throw"Type error: unexpected '"+a.constructor.name+"', expecting 'GenLanguageDef.LanguageDef'";var ra=Qa(y(bb)),Sa=n(G(N(a.commentLine)))(W,y(function(e){return e!="\n"}))(m,null).resolve(),v=Ja(C(a.commentEnd+a.commentStart)),mc=[k(G(N(a.commentEnd)),m(null)),"<|>",k(Qa(xb(v)),d),"<|>",k(P(v),d),"<?>","end of comment"].resolve(),nc=[k(G(N(a.commentEnd)),m(null)),"<|>",k(g,f),"<|>",k(Qa(xb(v)),f),"<|>",
k(P(v),f),"<?>","end of comment"].resolve();v=a.nestedComments?nc:mc;var ub=k(G(N(a.commentStart)),v);v=ab(a.commentLine);var Q=ab(a.commentStart),lc=(v&&Q?[W,[ra,"<?>",""]]:v?[W,[ra,"<|>",ub,"<?>",""]]:Q?[W,[ra,"<|>",Sa,"<?>",""]]:[W,[ra,"<|>",Sa,"<|>",ub,"<?>",""]]).resolve(),wb=b(";"),vb=b(",");ra=b(".");Sa=b(":");v=Wa("abfnrtv\\\"'","a\u0008\u000c\n\r\t\u000b\\\"'");Q=Wa(["NUL","SOH","STX","ETX","EOT","ENQ","ACK","BEL","DLE","DC1","DC2","DC3","DC4","NAK","SYN","ETB","CAN","SUB","ESC","DEL"]+["BS",
"HT","LF","VT","FF","CR","SO","SI","EM","FS","GS","RS","US","SP"],["NUL","SOH","STX","ETX","EOT","ENQ","ACK","BEL","DLE","DC1","DC2","DC3","DC4","NAK","SYN","ETB","CAN","SUB","ESC","DEL"]+["BS","HT","LF","VT","FF","CR","SO","SI","EM","FS","GS","RS","US","SP"]);v=ob(z(S,v));var U=ob(z(I,Q));Q=y(function(e){return e!='"'&&e!="\\"&&e>"\u0016"});var ga=p("&"),Ga=n(Ba,yb)(p("\\"),"<?>","end of string gap").resolve(),Ha=n("code","<-",M,"<|>",k(p("o"),F(8,zb)),"<|>",k(p("x"),F(16,Ab)))(u(function(e){return toEnum(Ea(e.code))})).resolve(),
X=n(p("^"))("code","<-",sc)(u(function(e){return toEnum(fromEnum(e.code)-fromEnum("A"))})).resolve();U=[v,"<|>",Ha,"<|>",U,"<|>",X,"<?>","escape code"].resolve();v=k(p("\\"),U);v=[y(function(e){return e!="'"&&e!="\\"&&e>"\u0016"}),"<|>",v,"<?>","literal character"].resolve();v=[c,[ea,p("'"),[p("'"),"<?>","end of character"],v],"<?>","character"].resolve();ga=n(p("\\"))(n(Ga)(m,V.Nothing),"<|>",n(ga)(m,V.Nothing),"<|>",n("esc","<-",U)(O,V.Just,"esc")).resolve();Q=[n("c","<-",Q)(O,V.Just,"c"),"<|>",
ga,"<?>","string character"].resolve();Q=c([n("str","<-",ea,p('"'),[p('"'),"<?>","end of string"],[da,Q])(u,function(e){return va(Z(Jb)(sa,Z(R)),"",e.str)}),"<?>","literal string"].resolve());var fa=F(10,Bb);ga=n(P,"xX")(F,16,Ab).resolve();Ga=n(P,"oO")(F,8,zb).resolve();var Zc=[n(p("."))("digits","<-",Ba,Bb,"<?>","fraction")(u,function(e){return va(la,0,e.digits)}),"<?>","fraction"].resolve();U=[[p("-"),">>",m,Nb],"<|>",[p("+"),">>",m,sa],"<|>",m,sa].resolve();var qc=[n(P,"eE")("f","<-",U)("e","<-",
fa,"<?>","exponent")(O,ma,"f","e"),"<?>","exponent"].resolve();Ha=n("n","<-",fa)(function(e,l,s){return aa(l.n)(e,l,s)}).resolve();X=n("n","<-",fa)(function(e,l,s){return Pa(na.Left(l.n),xa(l.n))(e,l,s)}).resolve();var ta=[n("n","<-",ga,"<|>",Ga)(O,na.Left,"n"),"<|>",X,"<|>",xa(0),"<|>",m,na.Left(0)].resolve(),Ia=[k(p("0"),ta),"<|>",X].resolve();ta=[[n(p,"0")(ga,"<|>",Ga,"<|>",fa,"<|>",m,0),"<?>",""].resolve(),"<|>",fa].resolve();X=n("f","<-",c,U)("n","<-",ta)(u,function(e){return e.f(e.n)});U=[c,
Ia,"<?>","number"].resolve();Ha=[c,Ha,"<?>","float"].resolve();X=[c,X,"<?>","integer"].resolve();ta=[c,ta,"<?>","natural"].resolve();Ia=[n("c","<-",a.opStart)("cs","<-",da,a.opLetter)(O,Za,"c","cs"),"<?>","operator"].resolve();Ia=[c,"$",G,"$",n("name","<-",Ia)(function(e,l,s){return($(l.name)?Na("reserved operator "+l.name):m(l.name))(e,l,s)})].resolve();var Cb=[n("c","<-",a.identStart)("cs","<-",da,a.identLetter)(O,Za,"c","cs"),"<?>","identifier"].resolve();Cb=[c,"$",G,"$",n("name","<-",Cb)(function(e,
l,s){return(bd(l.name)?Na("reserved word "+l.name):m(l.name))(e,l,s)})].resolve();var tc=Xa(a.reservedNames),cd=a.caseSensitive?tc:z(function(e){return e.toLowerCase()},tc);return sb.TokenParser(ka,{identifier:Cb,reserved:ad,operator:Ia,reservedOp:ya,charLiteral:v,stringLiteral:Q,natural:ta,integer:X,float_:Ha,naturalOrFloat:U,decimal:fa,hexadecimal:ga,octal:Ga,symbol:b,lexeme:c,whiteSpace:lc,parens:h,braces:j,angles:i,brackets:r,squares:r,semi:wb,comma:vb,colon:Sa,dot:ra,semiSep:L,semiSep1:Ma,commaSep:t,
commaSep1:D})}var x,xc={}.toString,yc=[].slice,sa=function(a){return a},J=Z(function(a,b){return a(b)}),oc=parseInt,Ea=sa,pc=sa,ha=window.JSParsec={};A(ha,{curry:Z,const_:Fb,isArray:ia,isDefined:Ua,slice:C,foldl:Gb,foldr:va,map:z,filter:Hb,indexOf:Va,lastIndexOf:Ib,zip:Wa,sort:Xa,nub:Ja,maybe:Jb,compare:Kb,compose:Lb,compose1:Mb,call:J,id:sa,flip:Ya,cons:R,consJoin:Za,replicate:$a,negate:Nb,null_:ab,elem:Ka,isSpace:bb,isUpper:Ob,isLower:Pb,isAlpha:cb,isAlphaNum:Qb,isDigit:Rb,isHexDigit:db,isOctDigit:Sb,
digitToInt:eb,range:zc,extend:A,namespace:Dc,toInteger:oc,fromInteger:Ea,fromIntegral:pc,fst:Ac,snd:Bc,uncurry:Cc});var ka=new Tb;La.prototype.toString=Ub();La.prototype.dataConstructorToString=Ub(true);ja(V,[["Just","a"],"Nothing"]);ja(wa,["LT","EQ","GT"]);ja(na,[["Left","a"],["Right","b"]]);var oa={$:{func:J,fixity:ba(0)},".":{func:Mb,fixity:ba(9)},":":{func:R,fixity:ba(5)}};Array.prototype.resolve=function(){return ca(this)};var H=new gb;A(ha,{data:ja,ADT:La,record:ka,Maybe:V,Ordering:wa,Either:na,
operators:oa,infix:Vb,infixl:T,infixr:ba,arr:Hc,op:Jc,str:Ic,resolve:ca,recurse:H,Recurse:gb,cs:n});za.prototype={memoize:false,scrollTo:function(a){this.index=a;this.length=this.input.length-a;return this},scroll:function(a){this.index+=a;this.length-=a;return this},at:function(a){return this.input.charAt(this.index+a)},substring:function(a,b){return this.input.substring(a+this.index,(b||this.length)+this.index)},substr:function(a,b){return this.input.substring(a+this.index,b||this.length)},toString:function(){var a=
this.substring(0);return"PS at "+this.index+" "+(a.length?'"'+a+'"':"Empty")},getCached:function(a){if(this.memoize)if(a=this.cache[a])if(a=a[this.index]){this.index=a.index;this.length=a.length;return a}},putCached:function(a,b,c){if(!this.memoize)return false;c.index=this.index;c.length=this.length;var d=this.cache[a];d||(d=this.cache[a]={});d[b]=c}};var Mc=B(x),pb=Yb;H=pb;var ec=0,Db=function(a,b){function c(d,f,g){return{func:a,args:[d,f,function(h){return h.success?b(d,f,g):g(h)}]}}c.constructor=
o;return c},k=function(){function a(c,d,f){var g={},h=1,j=b.length,i=b[0];for(g.scope=d;h<j;++h)i=Db(i,b[h]);return i(c,g,f)}var b=z(hb,arguments);a.constructor=o;return a},O=Lb(u,lb),m=ac,uc=m,qa=bc,ua=qa,Y=function(a,b,c){return Aa(qa(a,b),c)},K=function(a,b,c,d){return Aa(Aa(qa(a,b),c),d)},gc=ua,Ta=Db,Eb=w,da=dc(false),Ba=dc(true),G=Oa(function(a,b,c,d){if(b.success)return b;c.scrollTo(d);return pa(b.expecting)}),W=function(a){return Oa(function(b,c){c=A({},c);c.ast=x;return c})(da(a),null)},p=
nb(function(a,b){if(b.length>0&&b.at(0)==a){b.scroll(1);return B(a)}return pa(a)}),y=nb(function(a,b){var c=b.at(0);if(b.length>0&&a(c)){b.scroll(1);return B(c)}return pa(c)}),N=function(a){return Oa(function(b,c,d,f){c.ast=c.ast.join("");c=A({},c);if(c.success)delete c.expecting;else c.expecting={at:f,expecting:a};if(!c.ast.length)c.ast=x;return c})(mb(z(p,a)),null)},Fa=Oa(function(a,b,c,d){if(!b.success){b=A({},b);b.expecting={at:d,expecting:a}}return b}),dd=nb(function(a,b){var c;if(typeof a==
"string")if(b.substring(0,a.length)==a){b.scroll(a.length);c=B(a)}else c=pa(a);else if(a.exec){var d=new RegExp("^"+a.source);c=b.substring(0);d=(d=(d=d.exec(c))&&d[0])&&d.length;c=c.substr(0,d);if(d){b.scroll(d);c=B(c)}else c=pa(a.source)}return c});A(oa,{"<-":{func:q,fixity:ba(-1)},">>=":{func:kb,fixity:T(1)},"=<<":{func:Ya(kb),fixity:ba(1)},">>":{func:Ta,fixity:T(1)},"*>":{func:Ta,fixity:T(4)},"<*":{func:cc,fixity:T(4)},"<$>":{func:qa,fixity:T(4)},"<*>":{func:Aa,fixity:T(4)},"<**>":{func:Z(Y)(Ya(J)),
fixity:T(4)},"<$":{func:function(a,b){return cc(uc(value),b)},fixity:T(4)},"<|>":{func:w,fixity:ba(1)},"<?>":{func:Fa,fixity:Vb(0)}});A(ha,{sequence:fc,run:Lc,Parser:o,ParseState:za,ps:Wb,toParser:hb,unexpected:Na,parsecMap:bc,fmap:qa,liftM:gc,liftM2:Y,liftM3:K,liftA:ua,liftA2:Y,liftA3:K,ap:Aa,parserBind:kb,parserReturn:ac,return_:m,pure:uc,parserFail:Xb,fail:Xb,parserZero:Yb,mzero:pb,empty:H,parserPlus:w,parserPlusN:Nc,mplus:Eb,do_:k,do2:Db,bind:q,ret:u,withBound:lb,returnCall:O,getParserState:Zb,
setParserState:$b,tokens:mb,many:da,many1:Ba,string:N,char_:p,satisfy:y,label:Fa,try_:G,skipMany:W,match:dd});var P=function(a){return Fa(y(function(b){return Ka(b,a)}),"oneOf("+a+")")},xb=function(a){return Fa(y(function(b){return!Ka(b,a)}),"noneOf("+a+")")},yb=[y,bb,"<?>","space"].resolve();ua=[W,yb,"<?>","white space"].resolve();Y=[p,"\n","<?>","new-line"].resolve();K=[p,"\t","<?>","tab"].resolve();var sc=[y,Ob,"<?>","uppercase letter"].resolve();Ta=[y,Pb,"<?>","lowercase letter"].resolve();J=
[y,Qb,"<?>","letter or digit"].resolve();H=[y,cb,"<?>","letter"].resolve();var Bb=[y,Rb,"<?>","digit"].resolve(),Ab=[y,db,"<?>","hexadecimal digit"].resolve(),zb=[y,Sb,"<?>","octal digit"].resolve();Eb=[y,Fb(true)].resolve();A(ha,{oneOf:P,noneOf:xb,space:yb,spaces:ua,newline:Y,tab:K,upper:sc,lower:Ta,alphaNum:J,letter:H,digit:Bb,hexDigit:Ab,octDigit:zb,anyChar:Eb});var ea=Z(function(a,b,c){return k(a,q("x",c),b,u("x"))});A(ha,{choice:ob,count:Sc,between:ea,option:Pa,optionMaybe:Oc,optional:Pc,skipMany1:Qa,
sepBy:qb,sepBy1:Ra,endBy:Rc,endBy1:Qc,sepEndBy:ic,sepEndBy1:hc,chainl:Uc,chainl1:kc,chainr:Tc,chainr1:jc,eof:Wc,notFollowedBy:rb,manyTill:Xc,lookAhead:Yc,anyToken:Vc});ja(Ca,[["LanguageDef",{commentStart:String,commentEnd:String,commentLine:String,nestedComments:Boolean,identStart:o,identLetter:o,opStart:o,opLetter:o,reservedNames:Array,reservedOpNames:Array,caseSensitive:Boolean}]]);ja(sb,[["TokenParser",{identifier:o,reserved:Function,operator:o,reservedOp:Function,charLiteral:o,stringLiteral:o,
natural:o,integer:o,float_:o,naturalOrFloat:o,decimal:o,hexadecimal:o,octal:o,symbol:Function,lexeme:Function,whiteSpace:o,parens:Function,braces:Function,angles:Function,brackets:Function,squares:Function,semi:o,comma:o,colon:o,dot:o,semiSep:Function,semiSep1:Function,commaSep:Function,commaSep1:Function}]]);A(ha,{GenLanguageDef:Ca,GenTokenParser:sb,makeTokenParser:tb});K=P(":!#$%&*+./<=>?@\\^|-~");ua=Ca.LanguageDef(ka,{commentStart:"",commentEnd:"",commentLine:"",nestedComments:true,identStart:[H,
"<|>",p("_")].resolve(),identLetter:[J,"<|>",P("_'")].resolve(),opStart:K,opLetter:K,reservedOpNames:[],reservedNames:[],caseSensitive:true});Y=Ca.LanguageDef(ka,{commentStart:"{-",commentEnd:"-}",commentLine:"--",nestedComments:true,identStart:H,identLetter:[J,"<|>",P,"_'"].resolve(),opStart:K,opLetter:K,reservedOpNames:[],reservedNames:[],caseSensitive:true});J=Ca.LanguageDef(ka,{commentStart:"/*",commentEnd:"*/",commentLine:"//",nestedComments:true,identStart:H,identLetter:[J,"<|>",P,"_'"].resolve(),
opStart:K,opLetter:K,reservedOpNames:[],reservedNames:[],caseSensitive:false});H=Y.update({reservedOpNames:["::","..","=","\\","|","<-","->","@","~","=>"],reservedNames:["let","in","case","of","if","then","else","data","type","class","default","deriving","do","import","infix","infixl","infixr","instance","module","newtype","where","primitive"]});var vc=H.update({identLetter:[H.identLetter,"<|>",p("#")].resolve(),reservedNames:H.reservedNames.concat(["foreign","import","export","primitive","_ccall_",
"_casm_","forall"])}),wc=J.update({reservedNames:["case","class","default","extends","import","in","let","new","of","package"],caseSensitive:true});A(ha,{emptyDef:ua,haskellStyle:Y,javaStyle:J,haskellDef:vc,mondrianDef:wc,getHaskell:function(){return tb(vc)},getMondrian:function(){return tb(wc)}})})();
